### ISSUE TITLE
Upgrad to 1.1.0 failed with error unable to recognize "": 

### ISSUE THREAD

**Issue by tobg** [piraeusdatastore/piraeus-operator#103]
Got the following error on trying upgrade 1.0.0 to 1.1.0.

helm upgrade piraeus-op -f ./helm-tobg/values.yaml ./piraeus-operator/charts/piraeus
Error: UPGRADE FAILED: [unable to recognize "": no matches for kind "LinstorController" in version "piraeus.linbit.com/v1", unable to recognize "": no matches for kind "LinstorSatelliteSet" in version "piraeus.linbit.com/v1"]

**Comment by WanzenBug** [comment]
I can't reproduce it in my setup. Does `kubectl get crds` show the expected crds? For a normal 1.0.0 install they should show
```
$ kubectl get crds
NAME                                                  CREATED AT
....
linstorcontrollers.piraeus.linbit.com                 2020-10-15T12:35:03Z
linstorcontrollersets.piraeus.linbit.com              2020-10-15T12:35:03Z
linstorcsidrivers.piraeus.linbit.com                  2020-10-15T12:35:03Z
linstornodesets.piraeus.linbit.com                    2020-10-15T12:35:03Z
linstorsatellitesets.piraeus.linbit.com               2020-10-15T12:35:03Z
...
```

**Comment by tobg** [comment]
I pulled from master. Release 1.1.0 is working.

**Comment by tobg** [comment]
Correction, Release 1.1.0 has the same issue. It's only on upgrade. Not install.

**Comment by tobg** [comment]
And yes, crd are missing

➜  piraeus-operator-1.1.0 git:(master) ✗ k get crd | grep linstor
linstorcsidrivers.piraeus.linbit.com                         2020-10-15T13:12:04Z

**Comment by tobg** [comment]
Just another issue after upgrade. etcd is not working anymore.

➜  piraeus-operator-1.1.0 git:(master) ✗ klf piraeus-op-etcd-0
Waiting for piraeus-op-etcd-0.piraeus-op-etcd to come up
ping: piraeus-op-etcd-0.piraeus-op-etcd: System error
Waiting for piraeus-op-etcd-0.piraeus-op-etcd to come up
ping: piraeus-op-etcd-0.piraeus-op-etcd: System error
Waiting for piraeus-op-etcd-0.piraeus-op-etcd to come up
Waiting for piraeus-op-etcd-1.piraeus-op-etcd to come up
ping: piraeus-op-etcd-1.piraeus-op-etcd: System error
Waiting for piraeus-op-etcd-1.piraeus-op-etcd to come up
ping: piraeus-op-etcd-1.piraeus-op-etcd: System error
Waiting for piraeus-op-etcd-1.piraeus-op-etcd to come up
ping: piraeus-op-etcd-1.piraeus-op-etcd: System error

**Comment by tobg** [comment]
I did a complete remove and reinstall, now it works again. I had to manually remove all linstor components and did a fresh installation, using existing etcd ofc.
