### ISSUE TITLE
Read only filesystem after reboot k8s nodes

### ISSUE THREAD

**Issue by tobg** [piraeusdatastore/piraeus-operator#104]
I got some pvc which are read only after reboot of k8s nodes.
linstor v l shows up to date.

root@piraeus-op-cs-controller-667d5b46fb-rx9nz:/# linstor v l | grep 2bb1
| k8w1      | pvc-60be9b00-f476-420b-bc07-a6e87f972bb1 | DfltDisklessStorPool |     0 |    1037 | /dev/drbd1037 |            | InUse  | Diskless |
| k8w2      | pvc-60be9b00-f476-420b-bc07-a6e87f972bb1 | lvm-any50            |     0 |    1037 | /dev/drbd1037 |   4.70 GiB | Unused | UpToDate |
| k8w3      | pvc-60be9b00-f476-420b-bc07-a6e87f972bb1 | lvm-any50            |     0 |    1037 | /dev/drbd1037 | 296.69 MiB | Unused | UpToDate |
| k8w4      | pvc-60be9b00-f476-420b-bc07-a6e87f972bb1 | lvm-any50            |     0 |    1037 | /dev/drbd1037 | 303.25 MiB | Unused | UpToDate |

How can I fix this?

**Comment by WanzenBug** [comment]
If the PVC currently in use by a Pod? It looks like a pod on k8w1 is using it (which means its open for RW). You can check the node journal and the current mount information to see why it is only accessible RO.

**Comment by tobg** [comment]
Thank's for this hint. k8w1 was not using it. I had to force remove the wrong claim by using  kubectl get volumeattachment and then delete the claim of k8w1.
