### ISSUE TITLE
Error on deploy new pvc. Existing one works.

### ISSUE THREAD

**Issue by tobg** [piraeusdatastore/piraeus-operator#106]
Got the following errors doing kubectl describe pvc name.
pvc wont get created.

  Warning  ProvisioningFailed    34s                linstor.csi.linbit.com_piraeus-op-csi-controller-5c65956bf4-s4t5h_d02bd753-670a-47cf-a6e4-4aed355fb8e8  failed to provision volume with StorageClass "linstor-sc-hdd": rpc error: code = Internal desc = CreateVolume failed for pvc-56019475-789d-469c-9694-278d711fb079: Message: 'Successfully set property key(s): StorPoolName' next error: Message: 'Successfully set property key(s): StorPoolName' next error: Message: 'Resource 'pvc-56019475-789d-469c-9694-278d711fb079' successfully autoplaced on 2 nodes'; Details: 'Used nodes (storage pool name): 'k8smaster (lvm-hdd)', 'k8w6 (lvm-hdd)'' next error: Message: 'Tie breaker resource 'pvc-56019475-789d-469c-9694-278d711fb079' created on k8w2' next error: Message: 'Resource-definition property 'DrbdOptions/Resource/quorum' updated from 'null' to 'majority' by auto-quorum' next error: Message: 'Resource-definition property 'DrbdOptions/Resource/on-no-quorum' updated from 'null' to 'io-error' by auto-quorum' next error: Message: '(Node: 'k8w2') Failed to adjust DRBD resource pvc-56019475-789d-469c-9694-278d711fb079'; Reports: '[5F99F200-4BC88-000024]' next error: Message: 'Created resource 'pvc-56019475-789d-469c-9694-278d711fb079' on 'k8w6'' next error: Message: 'Created resource 'pvc-56019475-789d-469c-9694-278d711fb079' on 'k8smaster''

**Comment by WanzenBug** [comment]
I'd be interested in the referenced error report from LINSTOR: 
```
kubectl exec deployment/piraeus-op-cs-controller -- linstor err show 5F99F200-4BC88-000024
```

**Comment by tobg** [comment]
ERROR REPORT 5F99F200-4BC88-000024

============================================================

Application:                        LINBIT�� LINSTOR
Module:                             Satellite
Version:                            1.9.0
Build ID:                           678acd24a8b9b73a735407cd79ca33a5e95eb2e2
Build time:                         2020-09-23T09:33:23+00:00
Error time:                         2020-10-28 22:46:25
Node:                               k8w2

============================================================

Reported error:
===============

Description:
    Failed to adjust DRBD resource pvc-56019475-789d-469c-9694-278d711fb079

Category:                           LinStorException
Class name:                         ResourceException
Class canonical name:               com.linbit.linstor.core.devmgr.exceptions.ResourceException
Generated at:                       Method 'adjustDrbd', Source file 'DrbdLayer.java', Line #699

Error message:                      Failed to adjust DRBD resource pvc-56019475-789d-469c-9694-278d711fb079

Error context:
    An error occurred while processing resource 'Node: 'k8w2', Rsc: 'pvc-56019475-789d-469c-9694-278d711fb079''

Call backtrace:

    Method                                   Native Class:Line number
    adjustDrbd                               N      com.linbit.linstor.layer.drbd.DrbdLayer:699
    process                                  N      com.linbit.linstor.layer.drbd.DrbdLayer:383
    process                                  N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:789
    processResourcesAndSnapshots             N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:335
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:145
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:268
    phaseDispatchDeviceHandlers              N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:924
    devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:627
    run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:545
    run                                      N      java.lang.Thread:834

Caused by:
==========

Description:
    Execution of the external command 'drbdadm' failed.
Cause:
    The external command exited with error code 1.
Correction:
    - Check whether the external program is operating properly.
    - Check whether the command line is correct.
      Contact a system administrator or a developer if the command line is no longer valid
      for the installed version of the external program.
Additional information:
    The full command line executed was:
    drbdadm -vvv adjust pvc-56019475-789d-469c-9694-278d711fb079

    The external command sent the following output data:
    drbdsetup new-resource pvc-56019475-789d-469c-9694-278d711fb079 2 --on-no-quorum=io-error --quorum=majority
    drbdsetup new-minor pvc-56019475-789d-469c-9694-278d711fb079 1122 0 --diskless


    The external command sent the following error information:
    New resource pvc-56019475-789d-469c-9694-278d711fb079
    New minor 1122 (vol:0)
    new-minor pvc-56019475-789d-469c-9694-278d711fb079 1122 0: sysfs node '/sys/devices/virtual/block/drbd1122' (already? still?) exists
    pvc-56019475-789d-469c-9694-278d711fb079: Failure: (161) Minor or volume exists already (delete it first)
    Command 'drbdsetup new-minor pvc-56019475-789d-469c-9694-278d711fb079 1122 0 --diskless' terminated with exit code 10


Category:                           LinStorException
Class name:                         ExtCmdFailedException
Class canonical name:               com.linbit.extproc.ExtCmdFailedException
Generated at:                       Method 'execute', Source file 'DrbdAdm.java', Line #555

Error message:                      The external command 'drbdadm' exited with error code 1


Call backtrace:

    Method                                   Native Class:Line number
    execute                                  N      com.linbit.linstor.layer.drbd.utils.DrbdAdm:555
    adjust                                   N      com.linbit.linstor.layer.drbd.utils.DrbdAdm:90
    adjustDrbd                               N      com.linbit.linstor.layer.drbd.DrbdLayer:680
    process                                  N      com.linbit.linstor.layer.drbd.DrbdLayer:383
    process                                  N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:789
    processResourcesAndSnapshots             N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:335
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:145
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:268
    phaseDispatchDeviceHandlers              N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:924
    devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:627
    run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:545
    run                                      N      java.lang.Thread:834


END OF ERROR REPORT.

**Comment by tobg** [comment]
Looks like there already exists a lvm drbd1122 which drbd tries to create. right?

**Comment by tobg** [comment]
After several retreys it worked.
