### ISSUE TITLE
A volume definition with the number 0 already exists in resource definition

### ISSUE THREAD

**Issue by tobg** [piraeusdatastore/piraeus-operator#110]
We get this error on pvc bounding. The status of the pvc is pending forever.

  Warning  ProvisioningFailed    7m43s                  linstor.csi.linbit.com_piraeus-op-csi-controller-66fd956c6d-7kv2n_f5010b7b-8089-4db2-9f7d-b7987f9898a9  failed to provision volume with StorageClass "linstor-sc-hdd": rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Normal   Provisioning          3m26s (x9 over 7m53s)  linstor.csi.linbit.com_piraeus-op-csi-controller-66fd956c6d-7kv2n_f5010b7b-8089-4db2-9f7d-b7987f9898a9  External provisioner is provisioning volume for claim "default/hdd-pvc-zabbix-mysql01-8bb0a103-7b21-4e4d-822d-71da9bdc08b3"
  Warning  ProvisioningFailed    3m26s (x8 over 7m42s)  linstor.csi.linbit.com_piraeus-op-csi-controller-66fd956c6d-7kv2n_f5010b7b-8089-4db2-9f7d-b7987f9898a9  failed to provision volume with StorageClass "linstor-sc-hdd": rpc error: code = Internal desc = CreateVolume failed for pvc-44c6873d-4875-4c86-9588-a55c2a520302: Message: 'A volume definition with the number 0 already exists in resource definition 'pvc-44c6873d-4875-4c86-9588-a55c2a520302'.'; Cause: 'The VolumeDefinition already exists'; Details: 'Volume definitions of resource: pvc-44c6873d-4875-4c86-9588-a55c2a520302'
  Normal   ExternalProvisioning  102s (x26 over 7m53s)  persistentvolume-controller                                                                             waiting for a volume to be created, either by external provisioner "linstor.csi.linbit.com" or manually created by system administrator

linstor v l showa this pvc with status:
 k8smaster ┊ pvc-44c6873d-4875-4c86-9588-a55c2a520302 ┊ lvm-hdd              ┊     0 ┊    1132 ┊ /dev/drbd1132 ┊   9.05 GiB ┊ Unused ┊ UpToDate ┊
┊ k8w6      ┊ pvc-44c6873d-4875-4c86-9588-a55c2a520302 ┊ lvm-hdd              ┊     0 ┊    1132 ┊ /dev/drbd1132 ┊   6.25 GiB ┊ Unused ┊ Outdated ┊

**Comment by WanzenBug** [comment]
Is this a volume restored from a snapshot/other volume? 

I know there is a bug in the current version of LINSTOR CSI that happens when creating a volume based on a snapshot/other volume takes too long. It should be enough to delete the volume definition in LINSTOR in that case:
```
linstor vd d pvc-44c6873d-4875-4c86-9588-a55c2a520302 0
```
on the next try LINSTOR should succeed

**Comment by tobg** [comment]
Yes it is. I try with deletion the vd. Thank you.

**Comment by tobg** [comment]
The deletion was not successful:

ERROR REPORT 5F9FBA28-4BC88-000004

============================================================

Application:                        LINBIT�� LINSTOR
Module:                             Satellite
Version:                            1.9.0
Build ID:                           678acd24a8b9b73a735407cd79ca33a5e95eb2e2
Build time:                         2020-09-23T09:33:23+00:00
Error time:                         2020-11-03 10:36:10
Node:                               k8w2

============================================================

Reported error:
===============

Category:                           Error
Class name:                         ImplementationError
Class canonical name:               com.linbit.ImplementationError
Generated at:                       Method 'ensureAllVlmDataDeleted', Source file 'DeviceHandlerImpl.java', Line #505

Error message:                      Layer 'DRBD did not delete the volume 0 of resource pvc-44c6873d-4875-4c86-9588-a55c2a520302 properly

Error context:
    An error occurred while processing resource 'Node: 'k8w2', Rsc: 'pvc-44c6873d-4875-4c86-9588-a55c2a520302''

Call backtrace:

    Method                                   Native Class:Line number
    ensureAllVlmDataDeleted                  N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:505
    processResourcesAndSnapshots             N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:384
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:145
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:268
    phaseDispatchDeviceHandlers              N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:924
    devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:627
    run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:545
    run                                      N      java.lang.Thread:834


END OF ERROR REPORT.

**Comment by tobg** [comment]
k8w2 is a diskless node.

**Comment by tobg** [comment]
I hab to remove the diskless resource to solve the issue.
