### ISSUE TITLE
Questions related to Piraeus usage

### ISSUE THREAD

**Issue by immanuelfodor** [piraeusdatastore/piraeus-operator#125]
Hi Everyone,

I've managed to start up the Piraeus Operator in an RKE k8s cluster with 3 CentOS 8 nodes, etcd with 3 replicas and persistence through hostPath volume, CSI snapshotter and Stork turned off, kernel injector replaced for CentOS 8, hosts prepared with drbd and kernel headers as required. The 3 VM live on LVM Thin provisioned by Proxmox, and all VMs have one device each (sda) for the OS and local node data. The backing storage is NVMe.

As far as I see, the storage documentation (https://github.com/piraeusdatastore/piraeus-operator/blob/master/doc/storage.md) supports managing ZFS and LVM (Thin) pools through the operator. Since I'm not running the k8s cluster on bare metal, I'd need to create new disks in Proxmox (sdb) and attach them to the VMs. This way I could use the "Preparing physical devices" section to add these new disks to Piraeus. Question 1: is this "multi-level" or nested LVM thin provisioning supported? I think these sub-LVM Thin volumes would not mess with the external LVM Thin as these can contain any filesystem or LVM partition on their own. Am I right?

Question 2: My second question is related to the host disks (sda). Could I use these disks to provision storage to the pods running in k8s by using a folder on the host disks? What I originally desired is to use the host VM filesystem to store data from pods in a highly available manner, replicated across VMs. Like a `hostPath` or `LocalVolume` PV but this wouldn't depend on a single node. I'd like to store SQLite databases which would be only accessed by one pod each. I've found network file storage highly unreliable with SQLite (DB file corruption, locking issues, etc) but since I have an NVMe disk, and Linstor/Piraeus seems to be fast, I hope I could achieve this. Maybe I'm just not familiar enough with Piraeus/Linstor to know this is not possible, and I need to stick to disks. If the folder would contain binary files for storing the written blocks, and not the actual files, that would also work. As a workaround, may a loopback device would work pointing to a file that would contain the LVM Thin storage on each host?

```
+------------------+
|                  |
|  VM       +------+--------+
|  running  |               |
|  RKE      |   sda (OS)    +<------+
|           |               |       |
|           +------+--------+       |
|                  |                |
|           +------+--------+       |
|           |               |       |
|           |   sdb (data)  +<---+  |
|           |               |    |  |
|           +------+--------+    |  |
|                  |             |  |
+------------------+             |  |
                                 |  |
+------------------+             |  |
|                  |             |  |
|  VM       +------+--------+    |  |
|  running  |               |    |  |
|  RKE      |   sda (OS)    +<------+
|           |               |    |  |
|           +------+--------+    |  |
|                  |             |  |
|           +------+--------+    |  |
|           |               |    |  |
|           |   sdb (data)  +<---+  |
|           |               |    |  |
|           +------+--------+    |  |
|                  |             |  |
+------------------+             |  |
                                 |  |
+------------------+             |  |
|                  |             |  |
|  VM       +------+--------+    |  |
|  running  |               |    |  |
|  RKE      |   sda (OS)    +<------+
|           |               |    |  |
|           +------+--------+    |  |
|                  |             |  |
|           +------+--------+    |  |
|           |               |    |  |
|           |   sdb (data)  +<---+  |
|           |               |    |  |
|           +------+--------+    |  |
|                  |             |  |
+------------------+             +  +

                           Linstor (Piraeus)
                           1. the whole sdb dev?
                           2. a folder on sda?
```

Question 3: Since I haven't provision storage through satellite sets yet, is this why I can't see any new `StorageClass` created in the cluster? If I check the contents of the non-operator Piraeus deployment (https://raw.githubusercontent.com/piraeusdatastore/piraeus/master/deploy/all.yaml), there are multiple storage classes defined. The operator only creates these when it has the satellites configured with storage? 

```bash
$ kubectl exec -it deployment.apps/piraeus-op-cs-controller -- bash

root@piraeus-op-cs-controller-7fb6c98656-zvx49:/# linstor n list
╭──────────────────────────────────────────────────────────────────────────────────────────────╮
┊ Node                                      ┊ NodeType   ┊ Addresses                  ┊ State  ┊
╞══════════════════════════════════════════════════════════════════════════════════════════════╡
┊ piraeus-op-cs-controller-7fb6c98656-zvx49 ┊ CONTROLLER ┊ 10.42.1.72:3366 (PLAIN)    ┊ Online ┊
┊ node1                                     ┊ SATELLITE  ┊ 192.168.1.201:3366 (PLAIN) ┊ Online ┊
┊ node2                                     ┊ SATELLITE  ┊ 192.168.1.202:3366 (PLAIN) ┊ Online ┊
┊ node3                                     ┊ SATELLITE  ┊ 192.168.1.203:3366 (PLAIN) ┊ Online ┊
╰──────────────────────────────────────────────────────────────────────────────────────────────╯

root@piraeus-op-cs-controller-7fb6c98656-zvx49:/# linstor n info
╭─────────────────────────────────────────────────────────────╮
┊ Node      ┊ Diskless ┊ LVM ┊ LVMThin ┊ ZFS/Thin ┊ File/Thin ┊
╞═════════════════════════════════════════════════════════════╡
┊ node1     ┊ +        ┊ +   ┊ +       ┊ -        ┊ +         ┊
┊ node2     ┊ +        ┊ +   ┊ +       ┊ -        ┊ +         ┊
┊ node3     ┊ +        ┊ +   ┊ +       ┊ -        ┊ +         ┊
╰─────────────────────────────────────────────────────────────╯
Unsupported storage providers:
 node1: 
  SPDK: IO exception occured when running 'rpc.py get_spdk_version': Cannot run program "rpc.py": error=2, No such file or directory
  ZFS_THIN: 'cat /sys/module/zfs/version' returned with exit code 1
  ZFS: 'cat /sys/module/zfs/version' returned with exit code 1
 node2: 
  SPDK: IO exception occured when running 'rpc.py get_spdk_version': Cannot run program "rpc.py": error=2, No such file or directory
  ZFS_THIN: 'cat /sys/module/zfs/version' returned with exit code 1
  ZFS: 'cat /sys/module/zfs/version' returned with exit code 1
 node3: 
  SPDK: IO exception occured when running 'rpc.py get_spdk_version': Cannot run program "rpc.py": error=2, No such file or directory
  ZFS_THIN: 'cat /sys/module/zfs/version' returned with exit code 1
  ZFS: 'cat /sys/module/zfs/version' returned with exit code 1

╭──────────────────────────────────────────╮
┊ Node      ┊ DRBD ┊ LUKS ┊ NVMe ┊ Storage ┊
╞══════════════════════════════════════════╡
┊ node1     ┊ +    ┊ -    ┊ +    ┊ +       ┊
┊ node2     ┊ +    ┊ -    ┊ +    ┊ +       ┊
┊ node3     ┊ +    ┊ -    ┊ +    ┊ +       ┊
╰──────────────────────────────────────────╯
Unsupported resource layers:
 node1: 
  LUKS: IO exception occured when running 'cryptsetup --version': Cannot run program "cryptsetup": error=2, No such file or directory
 node2: 
  LUKS: IO exception occured when running 'cryptsetup --version': Cannot run program "cryptsetup": error=2, No such file or directory
 node3: 
  LUKS: IO exception occured when running 'cryptsetup --version': Cannot run program "cryptsetup": error=2, No such file or directory

root@piraeus-op-cs-controller-7fb6c98656-zvx49:/# linstor v list
╭──────────────────────────────────────────────────────────────────────────────────────────╮
┊ Node ┊ Resource ┊ StoragePool ┊ VolNr ┊ MinorNr ┊ DeviceName ┊ Allocated ┊ InUse ┊ State ┊
╞══════════════════════════════════════════════════════════════════════════════════════════╡
╰──────────────────────────────────────────────────────────────────────────────────────────╯
```

Note: I have `cryptsetup` installed on the nodes, so I don't know why it's not available. However, my Helm values have an empty `operator.controller.luksSecret` value, maybe that's why.

Note: this is a home k8s cluster, not affiliated with my work, and I'm on holiday today. The initiator problem is Sonarr/Radarr corrupting their SQLite DBs on NFS storage through nfs-client-provisioner. I'm looking for a "more cloud-native" solution than Ceph, more performant than OpenEBS Jiva/cstor and Longhorn, and more stable than OpenEBS Mayastor. Linstor/Piraeus seemed like a really good alternative from multiple benchmarks, and easy to set up. It indeed looks promising, I really hope I can use it after getting to know it :) Rancher has a host path provisioner project that could share host storage with pods but it would still depend on the shared folder's node, and I'd like to have data replication among nodes.

**Comment by WanzenBug** [comment]
Re Question 1: I'm not an expert in Proxmox, but essentially, your VMs will only see a generic block device. They don't see anything "outside", so they also cannot interfere with the "outer" LVM (thin) metadata. So there is nothing to "support" from Piraeus/LINSTOR side, it's just as if you attached an actual disk.

Re Question 2: In short: that is not possible. Longer answer: Fundamentally, LINSTOR creates block storage of some kind. For example that can be a LVM Thin Volume, a ZVOL, ... Piraeus can then automatically create a filesystem on that volume so it can be used as a filesystem volume in Kubernetes.

As for the workaround: It could work, but was never tested. It would introduce another layer that may impact performance. Instead of directly reading and writing to the device, you first have to go through `loopdev -> filesystem -> disk`. So while it could work (LINSTOR even has a storage driver based on files, which uses loopdev internally), I would no recommend it and there is no documentation for it.

Question 3: The operator will not create any storage classes. You can create the LINSTOR storage pools via the operator, then generate your own storage classes using the storage pools. For example:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: three-replicas
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
parameters:
  autoPlace: "3"
  storagePool: $MYPOOL
  resourceGroup: three-replicas
```

**Comment by immanuelfodor** [comment]
Thank you for taking the time to answer, very helpful and clear explanation. I'll choose the separate disk (sdb) route then. 

If I ever want to increase the available disk size (e.g., starting with 8G then increasing it to 16G, not a bound PV resize but what is available for the `StorageClass` to schedule), could I simply do it outside on the host without the knowledge of Linstor (resizing the disk and then extending LVM Thin), or should I do the LVM operation with the Linstor CLI? For example `set-size` seems related but I'm not that familiar of the CLI's capabilities (yet):

```bash
root@piraeus-op-cs-controller-7fb6c98656-zvx49:/# linstor volume-definition
usage: linstor volume-definition [-h]
                                 {create, delete, drbd-options, list,
                                 list-properties, set-property, set-size} ...
linstor volume-definition: error: too few arguments
```

**Comment by WanzenBug** [comment]
Resize should happen on the host. Basically:
```
$ pvscan --cache # optional, depending on if the host uses lvmetad
$ pvresize /dev/sdb
  Physical volume "/dev/sdb" changed
  1 physical volume(s) resized or updated / 0 physical volume(s) not resized
$ lvextend /dev/linstor_pool/pool /dev/sdb
```

**Comment by immanuelfodor** [comment]
Superb, thank you! Closing this issue for now as I got all the answers that were not obvious from the existing guides. In the meantime, I managed to create and attach the new disks to the VMs, configured the satellite storagePool, Piraeus deployment works fine, just about to create the storage class and provision some volumes to pods. Exciting times ahead :)
