### ISSUE TITLE
Suspicious satellite logs

### ISSUE THREAD

**Issue by immanuelfodor** [piraeusdatastore/piraeus-operator#148]
I suspect the below WARN is thrown because we run Linstor dockerized, and not on the host, is it right? 

However, why are all satellite pods outputting capacity as 0 when they have 8G disks from which approx 7G is still free? Shouldn't they say something other than 0? This log is there from the first time I started experimenting with Piraeus, it's not new but I was always curious what does it mean and why 0 capacity is logged.

```
 linstor-satellite 09:50:08.376 [DeviceManager] WARN  LINSTOR/Satellite - SYSTEM - Not calling 'systemd-notify' as NOTIFY_SOCKET is null
 linstor-satellite 09:51:27.362 [MainWorkerPool-1] INFO  LINSTOR/Satellite - SYSTEM - SpaceTracking: Satellite aggregate capacity is 0 kiB, no errors
 linstor-satellite 01:15:00.542 [MainWorkerPool-1] INFO  LINSTOR/Satellite - SYSTEM - SpaceTracking: Satellite aggregate capacity is 0 kiB, no errors
 linstor-satellite 09:49:27.043 [MainWorkerPool-1] INFO  LINSTOR/Satellite - SYSTEM - LogArchive: Running log archive on directory: /var/log/linstor-satellite
 linstor-satellite 09:49:27.044 [MainWorkerPool-1] INFO  LINSTOR/Satellite - SYSTEM - LogArchive: No logs to archive.
 linstor-satellite 01:15:00.564 [MainWorkerPool-1] INFO  LINSTOR/Satellite - SYSTEM - SpaceTracking: Satellite aggregate capacity is 0 kiB, no errors
```

**Comment by WanzenBug** [comment]
Yes, the WARN stems from the `systemd` integration in LINSTOR detecting no running systemd (because it's running in container). Nothing to worry about in this case.

The SpaceTracking messages are a bug that we are currently investigating. It's only used in error reports and other statistics, so it can safely be ignored.

**Comment by immanuelfodor** [comment]
Okay, thanks! Should we keep this issue open for the bug? 

Regarding the statistics, I'm not aware of any kind of anonymous data collection or such. Is there something ongoing in any of the Piraeus/Linstor/DRBD services or one that can be opt-in or opt-out?

**Comment by WanzenBug** [comment]
> Should we keep this issue open for the bug?
Yes, you can keep it open as a reminder.

> Regarding the statistics, I'm not aware of any kind of anonymous data collection or such.
There is non. That was badly worded on my part. Some commercial users of LINSTOR need to report their used storage space from time to time. This "statistic" never leaves your systems unless you send it.

**Comment by WanzenBug** [comment]
Bug in question (regarding space tracking) was closed some time ago.
