### ISSUE TITLE
Securing components

### ISSUE THREAD

**Issue by vitobotta** [piraeusdatastore/piraeus-operator#153]
Hi! I am testing Piraeus now and I got it working, but without configuring TLS etc between components or for etcd. That part of the setup is a little complicated for me and I am not sure of how to proceed...

So the question is, what are the risks? I am using this with virtual servers with a cheap provider that don't have private network. Do I risk something if I use the setup as it is? If yes, is there a bit more detailed guide on securing the components?

Thanks!

**Comment by WanzenBug** [comment]
I assume you already had a look at [the security guide](../blob/master/doc/security.md)? If not please take a look. The current state is not ideal, as it requires a lot of manual work. We are thinking about adding support for some of the many automatic certificate management tools in Kubernetes, like cert-manager in the future. This should make the whole process a lot easier.

There is a risk ofsomeone targeting your machines and trying to extract the content of your volumes. If someone can spoof one of your servers, they can effectively intercept all control and sync traffic between your servers.

If you are running Kubernetes on servers in public network, I would recommend to enable encryption of your pod network. I think most of the network providers support some kind of encryption for the pod network. This would then also include the control-plane traffic of Piraeus.

**Comment by vitobotta** [comment]
So if I use Weave CNI with encryption enabled, is my setup secure? Thanks!

**Comment by WanzenBug** [comment]
That would encrypt all communication between your pods. That still leaves the possibility to read the traffic of DRBD. If possible, I would create a wireguard tunnel between your virtual servers. That way you can ensure that _all_ traffic not just between Pods is secure.

**Comment by vitobotta** [comment]
Gotcha, thanks!

**Comment by WanzenBug** [comment]
Securing the control plane got a lot easier since merging #263

**Comment by cometship** [comment]
So, even with encryption enabled in the CNI (like Cilium), would DRBD traffic still require separate encryption (via TLS) in v2?

**Comment by WanzenBug** [comment]
If you CNI already provides encryption you don't specifically need DRBD with TLS enabled. It can sometimes still be useful if you are trying to protect against _other_ cluster components potentially trying to access DRBD data.

**Comment by cometship** [comment]
Thank you for the quick response! 

> If you CNI already provides encryption you don't specifically need DRBD with TLS enabled. 

So pod-to-pod encryption is enough to also encrypt DRBD traffic? I guess as long as you **don't** use `hostNetwork: true`. Then you would need node-to-node encryption (Cilium supports that as a beta feature) or TLS.

> It can sometimes still be useful if you are trying to protect against other cluster components potentially trying to access DRBD data.

I guess for that we can also use the provided `NetworkPolicy`?
