### ISSUE TITLE
CSI cloning support

### ISSUE THREAD

**Issue by phoenix-bjoern** [piraeusdatastore/piraeus-operator#155]
While reading through the snapshot description (https://github.com/piraeusdatastore/piraeus-operator/blob/master/doc/optional-components.md#snapshot-support-components) I also found that K8S supports cloning of an existing PVC: https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/
I haven't found anything in the Piraeus documentation, only the Linstor guide describes two modes how to clone a resource (https://www.linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-clone-mode).

So my question is: Does the Piraeus CSI driver also support PVC creation from an existing PVC (aka cloning):
```apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloned-pvc
spec:
  storageClassName: my-csi-plugin
  dataSource:
    name: existing-src-pvc-name
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

And if yes, how is it technically implemented (snapshot+creation from snapshot or new volume+copying with dd)?

In case cloning is currently not implemented in the CSI driver, it would be a wonderful addition.

**Comment by WanzenBug** [comment]
Yes, cloning is already implemented.

It uses snapshots internally, so it has some limitations:
* Only works if the volume was created using a LINSTOR storage pool which supports snapshots (i.e. a LVMTHIN pool will work, normal "fat" LVM will not)
* The new volume will be placed on the same nodes as the original (this can later change during use, but you can't directly clone to a completely different node)

**Comment by phoenix-bjoern** [comment]
Makes sense, excellent!
Maybe we can use this ticket to add this to the docu (https://github.com/piraeusdatastore/piraeus-operator/blob/master/doc/optional-components.md) here?

**Comment by WanzenBug** [comment]
I'll close this issue since #155 was merged
