### ISSUE TITLE
Configure LINSTOR to also log to files

### ISSUE THREAD

**Issue by WanzenBug** [piraeusdatastore/piraeus-operator#166]
Right now LINSTOR only logs to stdout, i.e. the logs are only available via Kubernetes logs. This is a problem when trying to access the logs from inside the container, i.e. `linstor sos-report create`.

We should configure controller and satellite to actually log in their log directory. This probably needs to be done via the logback.xml config. A useful snippet may be:
```
sed 's/<!-- <appender-ref ref="FILE" /> -->/<appender-ref ref="FILE" />/g' logback.xml
```

**Comment by JoelColledge** [comment]
Good idea. Perhaps with a different separator for sed :slightly_smiling_face:

```sed
s#<!-- <appender-ref ref="FILE" /> -->#<appender-ref ref="FILE" />#
```

**Comment by WanzenBug** [comment]
Might be worth to just directly change this file in our the piraeus-server image.

**Comment by JoelColledge** [comment]
That sounds like a good solution to me. Maybe check how large these files can get. Logback can do log rotation etc so we just need to ensure that it is configured.
