### ISSUE TITLE
cn values has missing many images

### ISSUE THREAD

**Issue by Rand01ph** [piraeusdatastore/piraeus-operator#191]
I try to use value.cn.yaml to deploy piraeus, but many images pull error.
such as: `daocloud.io/piraeus/piraeus-csi:v0.13.0 not found: manifest unknown: manifest unknown`

**Comment by WanzenBug** [comment]
@alexzhc Do you know anything about that?

**Comment by WanzenBug** [comment]
Still seems to be an issue.

Sadly, I'm not sure how this works on the daocloud side (maybe @alexzhc can jump in?). I'm guessing someone has to manually copy the images. Could we automate that process?

We currently automatically deploy to https://hub.docker.com/u/piraeusdatastore and https://quay.io/organization/piraeusdatastore.
Is there an equivalent free service that is suited for Chinese users? Then we could maybe automatically integrate that.

**Comment by WanzenBug** [comment]
daocloud hosts a new registry mirror, with updated images.
