### ISSUE TITLE
How to make piraeus node use dedicated network for drbd replication

### ISSUE THREAD

**Issue by redtex** [piraeusdatastore/piraeus-operator#196]
There is no described options how to use dedicated network for drbd replication

**Comment by WanzenBug** [comment]
Yeah, sorry about that, nobody has gotten around to documenting it yet.

The gist is this:
* Add a new net interface in linstor: `linstor node interface create <nodename> drbd_link <interface-ip>`
* Set the `PrefNic` property on (almost) any Linstor object: `linstor node set-property <nodename> PrefNic drbd_link`
  you can also just set in on a storage pool to let only that storage pool use the network, or on a resource-group, or on the controler, etc...

**Comment by JoelColledge** [comment]
There is [some general Linstor documentation](https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-managing_network_interface_cards) for this which is basically the same as the steps that @WanzenBug describes.

**Comment by redtex** [comment]
Thank you for fast answer !!!
But point is not to make it by ad-hoc commands, but set it in deployment code, in case of helm it must be some keys in values.yaml
Is it possible in present state of piraeus helm chart, or it a kind of feature request ?
