### ISSUE TITLE
Ping problems for piraeus-operator-etcd (missing setcap NET_RAW ?)

### ISSUE THREAD

**Issue by Dr-Shadow** [piraeusdatastore/piraeus-operator#204]
Hello, I'm having issues recently to deploy piraeus-operator on a self hosted kubernetes 1.22 from scratch.
For tests, I used etcd with root user (I removed securitycontext for the etcd instances).
It seems etcd is missing some capabilites in the security context unless I'm mistaken.

➜  infra git:(master) ✗ kubectl logs -n piraeus-system piraeus-operator-etcd-0
[...]
Waiting for piraeus-operator-etcd-0.piraeus-operator-etcd to come up
ping: socket: Address family not supported by protocol
[...]

➜  infra git:(master) ✗ kubectl exec -it -n piraeus-system piraeus-operator-etcd-0 -- whoami
root

➜  infra git:(master) ✗ kubectl exec -it -n piraeus-system piraeus-operator-etcd-0 -- ping -4 google.fr
ping: socket: Operation not permitted
command terminated with exit code 2

1 master / 3 nodes Kubernetes 1.22 on Ubuntu 21.04 / CRI-O

**Comment by WanzenBug** [comment]
Hello, thanks for reporting this issue.

Have you changed anything else on your system? I was under the impression that `CAP_NET_RAW` is on by default. But maybe that changed in recent ubuntu/cri-o versions?

**Comment by Dr-Shadow** [comment]
CRI-O version is 1.21.2

I will dig into this issue the next days, I got piraeus working probably by adding setcap NET_RAW. I can't confirm this yet because this "could" have been a network issue.

For anyone wondering where I could set etcd capabilities and without rootless for debug I got this :

```
diff --git a/charts/piraeus/charts/etcd/templates/statefulset.yaml b/charts/piraeus/charts/etcd/templates/statefulset.yaml
index c28fafe..eae5275 100755
--- a/charts/piraeus/charts/etcd/templates/statefulset.yaml
+++ b/charts/piraeus/charts/etcd/templates/statefulset.yaml
@@ -50,15 +50,12 @@ spec:
 {{- if .Values.tolerations }}
       tolerations:
 {{ toYaml .Values.tolerations | indent 8 }}
-{{- end }}
-      securityContext:
-{{- if .Values.podsecuritycontext }}
-{{ toYaml .Values.podsecuritycontext | indent 8 }}
-{{- else }}
-{{ include "operator.defaultpodsecuritycontext" $ | indent 8 }}
 {{- end }}
       containers:
       - name: {{ template "etcd.fullname" . }}
+        securityContext:
+          capabilities:
+            add: ["NET_RAW"]
         image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
         imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
         ports:
```

**Comment by Dr-Shadow** [comment]
The problem is still here with Kubernetes 1.22.1 / CRI-O 1.22 / piraeus-operator 1.60
The same patch resolves the issue for me

**Comment by Dr-Shadow** [comment]
I just found out why NET_RAW is dropped for CRI-O

"CRI-O now runs containers without NET_RAW and SYS_CHROOT capabilities by default. This can result in permission denied errors when the container tries to do something that would require either of these capabilities. For instance, using ping requires NET_RAW, unless the container is given the sysctl net.ipv4.ip_forward. Further, if you have a container that runs buildah or configures RPMs, they may fail without SYS_CHROOT. Ultimately, the dropped capabilities are worth it, as the majority of containers don’t need them. The fewer capabilities CRI-O gives out by default, the more secure it is by default. (#3119, @haircommander)"

https://cri-o.github.io/cri-o/v1.18.0.html

**Comment by WanzenBug** [comment]
Thank you for the investigation and the PR!

If etcd is now working for you, please close this issue.

**Comment by Dr-Shadow** [comment]
This is perfectly working on master, I'm just looking forward to get stork scheduler back on kubernetes then :)
