### ISSUE TITLE
Stork-scheduler missing flag on kube-scheduler-amd64

### ISSUE THREAD

**Issue by Dr-Shadow** [piraeusdatastore/piraeus-operator#205]
Stork-scheduler is crashing on a fresh install of kubernetes 1.22

➜  ~ kubectl logs -n piraeus-system piraeus-operator-stork-scheduler-5f757b489f-b52gm
Error: unknown flag: --scheduler-name

Probably related to kubernetes/kubernetes#102805

> The deprecated flag --hard-pod-affinity-symmetric-weight and --scheduler-name have been removed from kube-scheduler. Use ComponentConfig instead to configure those parameters.

**Comment by WanzenBug** [comment]
Thank for bringing this up.

For now, you can work around this issue by specifying an alternative (older) scheduler tag:

```
helm install ... --set stork.schedulerTag=v1.21.0
```

However, what you will find is that Stork itself doesn't seem to work on 1.22 at all. They do some checks for CRDs using the old v1beta1 api, which was removed in 1.22. So I think for now the only way is to disable STORK on 1.22 completely.
