### ISSUE TITLE
Unexpected physical storage list response. Null pointer exception.

### ISSUE THREAD

**Issue by tobg** [piraeusdatastore/piraeus-operator#206]
Hi,

using piraeus 1.5.1. One node is in unknown status. A reboot did not help.

This is the error from the controller:

root@piraeus-op-cs-controller-5bf989d799-h2x8z:/# linstor error-reports show 611BEAD6-00000-000373
ERROR REPORT 611BEAD6-00000-000373

============================================================

Application:                        LINBIT�� LINSTOR
Module:                             Controller
Version:                            1.13.0
Build ID:                           37c02e20aa52f26ef28ce4464925d9e53327171c
Build time:                         2021-06-21T06:45:49+00:00
Error time:                         2021-08-17 17:09:14
Node:                               piraeus-op-cs-controller-5bf989d799-h2x8z

============================================================

Reported error:
===============

Category:                           RuntimeException
Class name:                         NullPointerException
Class canonical name:               java.lang.NullPointerException
Generated at:                       Method 'listPhysicalStorageInScope', Source file 'CtrlPhysicalStorageApiCallHandler.java', Line #94

Asynchronous stage backtrace:

    Error has been observed at the following site(s):
        |_ checkpoint ? list physical storage
    Stack trace:

Call backtrace:

    Method                                   Native Class:Line number
    listPhysicalStorageInScope               N      com.linbit.linstor.core.apicallhandler.controller.CtrlPhysicalStorageApiCallHandler:94

Suppressed exception 1 of 1:
===============
Category:                           RuntimeException
Class name:                         OnAssemblyException
Class canonical name:               reactor.core.publisher.FluxOnAssembly.OnAssemblyException
Generated at:                       Method 'listPhysicalStorageInScope', Source file 'CtrlPhysicalStorageApiCallHandler.java', Line #94

Error message:
Error has been observed at the following site(s):
        |_ checkpoint ��� list physical storage
Stack trace:

Call backtrace:

    Method                                   Native Class:Line number
    listPhysicalStorageInScope               N      com.linbit.linstor.core.apicallhandler.controller.CtrlPhysicalStorageApiCallHandler:94
    doInScope                                N      com.linbit.linstor.core.apicallhandler.ScopeRunner:147
    lambda$fluxInScope$0                     N      com.linbit.linstor.core.apicallhandler.ScopeRunner:75
    call                                     N      reactor.core.publisher.MonoCallable:91
    trySubscribeScalarMap                    N      reactor.core.publisher.FluxFlatMap:126
    subscribeOrReturn                        N      reactor.core.publisher.MonoFlatMapMany:49
    subscribe                                N      reactor.core.publisher.Flux:8343
    onNext                                   N      reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain:188
    request                                  N      reactor.core.publisher.Operators$ScalarSubscription:2344
    onSubscribe                              N      reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain:134
    subscribe                                N      reactor.core.publisher.MonoCurrentContext:35
    subscribe                                N      reactor.core.publisher.Mono:4252
    subscribeWith                            N      reactor.core.publisher.Mono:4363
    subscribe                                N      reactor.core.publisher.Mono:4223
    subscribe                                N      reactor.core.publisher.Mono:4159
    subscribe                                N      reactor.core.publisher.Mono:4131
    doFlux                                   N      com.linbit.linstor.api.rest.v1.RequestHelper:304
    lambda$listPhysicalStorage$1             N      com.linbit.linstor.api.rest.v1.PhysicalStorage:102
    safeAsyncResponse                        N      com.linbit.linstor.api.rest.v1.RequestHelper:324
    listPhysicalStorage                      N      com.linbit.linstor.api.rest.v1.PhysicalStorage:71
    invoke                                   N      jdk.internal.reflect.GeneratedMethodAccessor21:unknown
    invoke                                   N      jdk.internal.reflect.DelegatingMethodAccessorImpl:43
    invoke                                   N      java.lang.reflect.Method:566
    lambda$static$0                          N      org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory:52
    run                                      N      org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1:124
    invoke                                   N      org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher:167
    doDispatch                               N      org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker:159
    dispatch                                 N      org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher:79
    invoke                                   N      org.glassfish.jersey.server.model.ResourceMethodInvoker:469
    apply                                    N      org.glassfish.jersey.server.model.ResourceMethodInvoker:391
    apply                                    N      org.glassfish.jersey.server.model.ResourceMethodInvoker:80
    run                                      N      org.glassfish.jersey.server.ServerRuntime$1:253
    call                                     N      org.glassfish.jersey.internal.Errors$1:248
    call                                     N      org.glassfish.jersey.internal.Errors$1:244
    process                                  N      org.glassfish.jersey.internal.Errors:292
    process                                  N      org.glassfish.jersey.internal.Errors:274
    process                                  N      org.glassfish.jersey.internal.Errors:244
    runInScope                               N      org.glassfish.jersey.process.internal.RequestScope:265
    process                                  N      org.glassfish.jersey.server.ServerRuntime:232
    handle                                   N      org.glassfish.jersey.server.ApplicationHandler:680
    service                                  N      org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer:356
    run                                      N      org.glassfish.grizzly.http.server.HttpHandler$1:200
    doWork                                   N      org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker:569
    run                                      N      org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker:549
    run                                      N      java.lang.Thread:829

END OF ERROR REPORT.

**Comment by tobg** [comment]
The unknown node shows the following: No currently configured DRBD found

**Comment by WanzenBug** [comment]
Might be something for the the folks at https://github.com/linbit/linstor-server

What's the output of lsblk on the node?

**Comment by tobg** [comment]
Thanks. Will ask over there as well.

➜  /opt/k8s git:(master) ✗ sudo lsblk
NAME                                                                           MAJ:MIN  RM   SIZE RO TYPE MOUNTPOINT
loop0                                                                            7:0     0  32.3M  1 loop /snap/snapd/12704
loop1                                                                            7:1     0  61.8M  1 loop /snap/core20/1081
loop2                                                                            7:2     0  68.3M  1 loop /snap/lxd/21260
loop3                                                                            7:3     0  68.2M  1 loop /snap/lxd/21039
sda                                                                              8:0     0   300G  0 disk
├─linstor_lvm--std--ha-lvm--std--ha_tmeta                                      253:0     0    76M  0 lvm
│ └─linstor_lvm--std--ha-lvm--std--ha-tpool                                    253:2     0 299.9G  0 lvm
│   ├─linstor_lvm--std--ha-lvm--std--ha                                        253:3     0 299.9G  1 lvm
│   ├─linstor_lvm--std--ha-pvc--7d8bce6c--5b90--4f04--9065--95decf31281c_00000 253:4     0    50G  0 lvm
│   ├─linstor_lvm--std--ha-pvc--c5f62807--3f42--4ad5--a05f--b3629e6e0663_00000 253:5     0  18.6G  0 lvm
│   ├─linstor_lvm--std--ha-pvc--d4eba29a--0c07--403c--ace4--5933d0a969c4_00000 253:6     0   3.7G  0 lvm
│   │ └─drbd1371                                                               147:1371  0   3.7G  0 disk /var/lib/kubelet/pods/245ed3ef-a1f0-4dae-a821-ce7d3c6c8d30/volumes/kubernetes.io~csi/pvc-d4eba29a-0c07-40
│   ├─linstor_lvm--std--ha-pvc--ab15da6d--8606--48b9--8e56--fed9d43e5de4_00000 253:7     0    15G  0 lvm
│   │ └─drbd1330                                                               147:1330  0    15G  0 disk
│   ├─linstor_lvm--std--ha-pvc--e8f7d0a5--9ef3--46ce--80b2--c12fe03880d4_00000 253:8     0     2G  0 lvm
│   │ └─drbd1353                                                               147:1353  0     2G  0 disk /var/lib/kubelet/pods/7c10b0fc-fe69-4dc7-b8b9-c689ec7a9f76/volumes/kubernetes.io~csi/pvc-e8f7d0a5-9ef3-46
│   ├─linstor_lvm--std--ha-pvc--f88c3dfd--77dc--42d7--9af9--aec4bb1a98d8_00000 253:9     0    10G  0 lvm
│   │ └─drbd1372                                                               147:1372  0    10G  0 disk
│   ├─linstor_lvm--std--ha-pvc--4abbcce4--047d--4747--a3a0--b1f55ae7bece_00000 253:10    0     2G  0 lvm
│   │ └─drbd1373                                                               147:1373  0     2G  0 disk
│   ├─linstor_lvm--std--ha-pvc--abee0347--6382--4228--adec--7e4346fdbbc9_00000 253:11    0    70G  0 lvm
│   │ └─drbd1349                                                               147:1349  0    70G  0 disk
│   ├─linstor_lvm--std--ha-pvc--aa6eff29--265d--47e5--a2c0--dc023d07fe29_00000 253:12    0    20G  0 lvm
│   │ └─drbd1347                                                               147:1347  0    20G  0 disk
│   ├─linstor_lvm--std--ha-pvc--78f419c4--829f--465e--bd85--8ac83e6608ff_00000 253:13    0   4.7G  0 lvm
│   │ └─drbd1281                                                               147:1281  0   4.7G  0 disk /var/lib/kubelet/pods/1997958e-feb7-488d-ac2d-84bf399ac08f/volumes/kubernetes.io~csi/pvc-78f419c4-829f-46
│   ├─linstor_lvm--std--ha-pvc--268ded0d--a422--4bb5--90f7--3a17dd946690_00000 253:14    0  37.3G  0 lvm
│   │ └─drbd1348                                                               147:1348  0  37.3G  0 disk
│   ├─linstor_lvm--std--ha-pvc--95f7822a--93a7--49eb--ac46--75445738f4e7_00000 253:15    0    50G  0 lvm
│   │ └─drbd1331                                                               147:1331  0    50G  0 disk
│   ├─linstor_lvm--std--ha-pvc--f88c3dfd--77dc--42d7--9af9--aec4bb1a98d8_00000_snapshot--75b987a4--9ff4--4faf--990b--2d4712a9210f
│   │                                                                          253:16    0    10G  0 lvm
│   ├─linstor_lvm--std--ha-pvc--268ded0d--a422--4bb5--90f7--3a17dd946690_00000_snapshot--ee73c159--206a--4353--aaef--2004ef7b8b68
│   │                                                                          253:17    0  37.3G  0 lvm
│   ├─linstor_lvm--std--ha-pvc--e8f7d0a5--9ef3--46ce--80b2--c12fe03880d4_00000_snapshot--f55cfe7a--44ff--487f--abb3--c36a9576e765
│   │                                                                          253:18    0     2G  0 lvm
│   ├─linstor_lvm--std--ha-pvc--95f7822a--93a7--49eb--ac46--75445738f4e7_00000_snapshot--daeb3667--24a6--4f46--aa28--3c027dbf5be7
│   │                                                                          253:19    0    50G  0 lvm
│   ├─linstor_lvm--std--ha-pvc--ab15da6d--8606--48b9--8e56--fed9d43e5de4_00000_snapshot--5b1f6e76--8d8a--445b--8ed2--5f9fff9b5f66
│   │                                                                          253:20    0    15G  0 lvm
│   ├─linstor_lvm--std--ha-pvc--d4eba29a--0c07--403c--ace4--5933d0a969c4_00000_snapshot--2d01d9ca--4f27--4fbd--a9df--820906f76e0a
│   │                                                                          253:21    0   3.7G  0 lvm
│   ├─linstor_lvm--std--ha-pvc--abee0347--6382--4228--adec--7e4346fdbbc9_00000_snapshot--e029984f--def2--45b9--93a3--75d6651c873e
│   │                                                                          253:22    0    70G  0 lvm
│   └─linstor_lvm--std--ha-pvc--aa6eff29--265d--47e5--a2c0--dc023d07fe29_00000_snapshot--875104b4--1acf--4685--a6f5--448167adb489
│                                                                              253:23    0    20G  0 lvm
└─linstor_lvm--std--ha-lvm--std--ha_tdata                                      253:1     0 299.9G  0 lvm
  └─linstor_lvm--std--ha-lvm--std--ha-tpool                                    253:2     0 299.9G  0 lvm
    ├─linstor_lvm--std--ha-lvm--std--ha                                        253:3     0 299.9G  1 lvm
    ├─linstor_lvm--std--ha-pvc--7d8bce6c--5b90--4f04--9065--95decf31281c_00000 253:4     0    50G  0 lvm
    ├─linstor_lvm--std--ha-pvc--c5f62807--3f42--4ad5--a05f--b3629e6e0663_00000 253:5     0  18.6G  0 lvm
    ├─linstor_lvm--std--ha-pvc--d4eba29a--0c07--403c--ace4--5933d0a969c4_00000 253:6     0   3.7G  0 lvm
    │ └─drbd1371                                                               147:1371  0   3.7G  0 disk /var/lib/kubelet/pods/245ed3ef-a1f0-4dae-a821-ce7d3c6c8d30/volumes/kubernetes.io~csi/pvc-d4eba29a-0c07-40
    ├─linstor_lvm--std--ha-pvc--ab15da6d--8606--48b9--8e56--fed9d43e5de4_00000 253:7     0    15G  0 lvm
    │ └─drbd1330                                                               147:1330  0    15G  0 disk
    ├─linstor_lvm--std--ha-pvc--e8f7d0a5--9ef3--46ce--80b2--c12fe03880d4_00000 253:8     0     2G  0 lvm
    │ └─drbd1353                                                               147:1353  0     2G  0 disk /var/lib/kubelet/pods/7c10b0fc-fe69-4dc7-b8b9-c689ec7a9f76/volumes/kubernetes.io~csi/pvc-e8f7d0a5-9ef3-46
    ├─linstor_lvm--std--ha-pvc--f88c3dfd--77dc--42d7--9af9--aec4bb1a98d8_00000 253:9     0    10G  0 lvm
    │ └─drbd1372                                                               147:1372  0    10G  0 disk
    ├─linstor_lvm--std--ha-pvc--4abbcce4--047d--4747--a3a0--b1f55ae7bece_00000 253:10    0     2G  0 lvm
    │ └─drbd1373                                                               147:1373  0     2G  0 disk
    ├─linstor_lvm--std--ha-pvc--abee0347--6382--4228--adec--7e4346fdbbc9_00000 253:11    0    70G  0 lvm
    │ └─drbd1349                                                               147:1349  0    70G  0 disk
    ├─linstor_lvm--std--ha-pvc--aa6eff29--265d--47e5--a2c0--dc023d07fe29_00000 253:12    0    20G  0 lvm
    │ └─drbd1347                                                               147:1347  0    20G  0 disk
    ├─linstor_lvm--std--ha-pvc--78f419c4--829f--465e--bd85--8ac83e6608ff_00000 253:13    0   4.7G  0 lvm
    │ └─drbd1281                                                               147:1281  0   4.7G  0 disk /var/lib/kubelet/pods/1997958e-feb7-488d-ac2d-84bf399ac08f/volumes/kubernetes.io~csi/pvc-78f419c4-829f-46
    ├─linstor_lvm--std--ha-pvc--268ded0d--a422--4bb5--90f7--3a17dd946690_00000 253:14    0  37.3G  0 lvm
    │ └─drbd1348                                                               147:1348  0  37.3G  0 disk
    ├─linstor_lvm--std--ha-pvc--95f7822a--93a7--49eb--ac46--75445738f4e7_00000 253:15    0    50G  0 lvm
    │ └─drbd1331                                                               147:1331  0    50G  0 disk
    ├─linstor_lvm--std--ha-pvc--f88c3dfd--77dc--42d7--9af9--aec4bb1a98d8_00000_snapshot--75b987a4--9ff4--4faf--990b--2d4712a9210f
    │                                                                          253:16    0    10G  0 lvm
    ├─linstor_lvm--std--ha-pvc--268ded0d--a422--4bb5--90f7--3a17dd946690_00000_snapshot--ee73c159--206a--4353--aaef--2004ef7b8b68
    │                                                                          253:17    0  37.3G  0 lvm
    ├─linstor_lvm--std--ha-pvc--e8f7d0a5--9ef3--46ce--80b2--c12fe03880d4_00000_snapshot--f55cfe7a--44ff--487f--abb3--c36a9576e765
    │                                                                          253:18    0     2G  0 lvm
    ├─linstor_lvm--std--ha-pvc--95f7822a--93a7--49eb--ac46--75445738f4e7_00000_snapshot--daeb3667--24a6--4f46--aa28--3c027dbf5be7
    │                                                                          253:19    0    50G  0 lvm
    ├─linstor_lvm--std--ha-pvc--ab15da6d--8606--48b9--8e56--fed9d43e5de4_00000_snapshot--5b1f6e76--8d8a--445b--8ed2--5f9fff9b5f66
    │                                                                          253:20    0    15G  0 lvm
    ├─linstor_lvm--std--ha-pvc--d4eba29a--0c07--403c--ace4--5933d0a969c4_00000_snapshot--2d01d9ca--4f27--4fbd--a9df--820906f76e0a
    │                                                                          253:21    0   3.7G  0 lvm
    ├─linstor_lvm--std--ha-pvc--abee0347--6382--4228--adec--7e4346fdbbc9_00000_snapshot--e029984f--def2--45b9--93a3--75d6651c873e
    │                                                                          253:22    0    70G  0 lvm
    └─linstor_lvm--std--ha-pvc--aa6eff29--265d--47e5--a2c0--dc023d07fe29_00000_snapshot--875104b4--1acf--4685--a6f5--448167adb489
                                                                               253:23    0    20G  0 lvm
sdb                                                                              8:16    0   300G  0 disk /mnt/backup
vda                                                                            252:0     0   160G  0 disk
├─vda1                                                                         252:1     0 159.9G  0 part /
├─vda14                                                                        252:14    0     4M  0 part
└─vda15                                                                        252:15    0   106M  0 part /boot/efi

**Comment by tobg** [comment]
Did a complete reinstall to solve it.
