### ISSUE TITLE
Stork Scheduler - stork-scheduler-account cannot list resource

### ISSUE THREAD

**Issue by stepa-ict** [piraeusdatastore/piraeus-operator#208]
Hi,

On the first place, I'd like to say thanks for a very good project. This works great.

Everything works fine, but today we tried to use stork scheduler. 
Pod stuck in pending state and in piraeus-op-stork-scheduler log says following:

```
Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: csistoragecapacities.storage.k8s.io is forbidden: User "system:serviceaccount:piraeus-operator:stork-scheduler-account" cannot list resource "csistoragecapacities" in API group "storage.k8s.io" at the cluster scope                                                                                                                                 

Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:serviceaccount:piraeus-operator:stork-scheduler-account" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
```

I am pretty sure that stok was working on some of the previous versions.

Does someone have advice on how to solve this?

Thanks,

**Comment by stepa-ict** [comment]
Hi,
maybe this will be useful for someone. 
I solved this by adding csidrivers csistoragecapacities resources under the apiGroups storage.k8s.io in cluster role stork-scheduler-role

This can be updated in piraeus-operator chart.

**Comment by junneyang** [comment]
> Hi, maybe this will be useful for someone. I solved this by adding csidrivers csistoragecapacities resources under the apiGroups storage.k8s.io in cluster role stork-scheduler-role
> 
> This can be updated in piraeus-operator chart.

same issue

@stepa-ict   How to solve this problem?， Thanks for your help!

![Image](https://github.com/user-attachments/assets/c8d292df-c02d-494e-abaa-45043729954c)

**Comment by junneyang** [comment]
any suggestions?
