### ISSUE TITLE
User manual?

### ISSUE THREAD

**Issue by aturetta** [piraeusdatastore/piraeus-operator#210]
After many failed attempts, I believe I installed the operator correctly

My issue is: why there is no user manual, something that explains how to use the operator to provision volumes for your workloads?
What is the next step, how the storage Class must be configured in your app's namespace?
I see the linstor system is very advanced and performant, but documentation is really scarce and not really friendly

Any pointers?

**Comment by JoelColledge** [comment]
[Here](https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#ch-kubernetes) are the docs you need. You can skip the deployment section since you are deploying with Piraeus.

We should refer to those docs from the README here. I'll leave this ticket open until that is done.

**Comment by JoelColledge** [comment]
The next steps after operator deployment are now documented here in this project: https://github.com/piraeusdatastore/piraeus-operator/tree/master/doc
