### ISSUE TITLE
Manager exited non-zero","error":"no matches for kind \"CSIDriver\" on upgraded kubernetes 1.22

### ISSUE THREAD

**Issue by tobg** [piraeusdatastore/piraeus-operator#212]
After we upgraded to kubernetes 1.22.1 piraeus-operator crashes with the following error.

time="2021-08-31T15:39:34Z" level=debug msg="update status in resource" Name=piraeus-op-cs Namespace=piraeus-system controller=LinstorController
I0831 15:39:34.280688       1 request.go:621] Throttling request took 1.027013825s, request: GET:https://10.96.0.1:443/apis/apps.kio.kasten.io/v1alpha1?timeout=32s
{"level":"error","ts":1630424374.333577,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"CSIDriver.storage.k8s.io","error":"no matches for kind \"CSIDriver\" in version \"storage.k8s.io/v1beta1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/source/source.go:105\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/manager/internal.go:514"}
{"level":"error","ts":1630424374.3336966,"logger":"cmd","msg":"Manager exited non-zero","error":"no matches for kind \"CSIDriver\" in version \"storage.k8s.io/v1beta1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tpiraeus-operator/cmd/manager/main.go:153\nruntime.main\n\t/opt/hostedtoolcache/go/1.15.13/x64/src/runtime/proc.go:204"}

**Comment by WanzenBug** [comment]
Last operator release uses some old versions of CRDs that are removed in v1.22. We upgraded those resource on the master branch already, but no release yet. You can try using the current master branch and the `:latest` operator image.

**Comment by tobg** [comment]
Thank you! That worked.
