### ISSUE TITLE
DeviceName none and volume not mounted after restart a pod

### ISSUE THREAD

**Issue by tobg** [piraeusdatastore/piraeus-operator#220]
It is not the first time I see this. Until now I hade to recretae the pvc and restore it from backup.

How to fix this without creating it new?

![image](https://user-images.githubusercontent.com/49125745/133658739-1666da76-32b6-418a-90e2-6ceef8d73a11.png)

**Comment by WanzenBug** [comment]
Hi!

I believe this is a bug recently discovered in LINSTOR, at least the output would match. Next LINSTOR release should contain a fix.

As a workaround, a `linstor node reconnect <nodename1>....` should get the device name back in order.

**Comment by tobg** [comment]
Hi!

Thank you very much. That did the trick. :)
