### ISSUE TITLE
empty volume after restarting the pod

### ISSUE THREAD

**Issue by phoenix-muecahit** [piraeusdatastore/piraeus-operator#231]
We have a problem after the update to version 1.5.1.

We had yesterday an issue, that one service started with an empty volume after the restart. Today we tried to find out how it happened and found this behavior:
When a PVC has one or more non "UpToDate" replicas, after restart of the pod it starts with an empty volume.
I tested it on a volume, you can see here the volume has one "broken" replica, the workload is scaled down to 0
![image](https://user-images.githubusercontent.com/90699413/139506508-4e191a7c-e73b-40da-9546-05cd59bee37f.png)

When I started the Pod again, you can see the volume just started from 0 and and created the initial data:
![image](https://user-images.githubusercontent.com/90699413/139506722-cf1948bd-6936-4bff-a957-f4fb064b1748.png)

I tested this behavior a few times, every time the same, it starts with an empty volume.
Before the version 1.5.1, we had 1.3.x, we updated first to 1.4.0, then to 1.5.0 and then to 1.5.1.

If we had a problem on one of the replicas when we had the version 1.3.x, we could solve it somehow, but the version 1.5.1 just fix it with fresh replicas and an empty volume. 

Does anybody has an idea, why this behavior happens?
We have many services running on linstor/piraeus, and would like to solve that problem as soon as possible.

**Comment by WanzenBug** [comment]
The red "UpToDate" state normally indicates some sort of connection issue. I'd check the output of "linstor r l" and also the kernel log (you can grep for the specific PVC), which hopefully has more information on why no connection could be established.
