### ISSUE TITLE
resource definitions are missing disk setting after upgrade

### ISSUE THREAD

**Issue by tauu** [piraeusdatastore/piraeus-operator#237]
After upgrading the piraeus-operator from 1.3.1 to 1.6.0, all pvc stopped working in the cluster. Investigating the issue for some time, revealed that for some reason no volume has an attached device anymore and correspondingly ist listed with a DfltDisklessStorPool storage pool.

```
LINSTOR ==> r l
┊ pvc-321752d7-2ffb-4972-b585-7f0823fd31dc ┊ node-1 ┊ 7000 ┊ Unused ┊ Ok    ┊ Diskless ┊ 2021-11-10 15:03:36 ┊

LINSTOR ==> v l
┊ node-1 ┊ pvc-321752d7-2ffb-4972-b585-7f0823fd31dc ┊ DfltDisklessStorPool ┊     0 ┊    1000 ┊ /dev/drbd1000 ┊           ┊ Unused ┊ Diskless┊
```

The devices are still present though and it is possible to attach them to the resource using drbdsetup 
```
drbdmeta /dev/k8data/pvc-321752d7-2ffb-4972-b585-7f0823fd31dc_00000 v09 /dev/k8data/pvc-321752d7-2ffb-4972-b585-7f0823fd31dc_00000 internal apply-al
drbdsetup attach 1000 /dev/k8data/pvc-321752d7-2ffb-4972-b585-7f0823fd31dc_00000 /dev/k8data/pvc-321752d7-2ffb-4972-b585-7f0823fd31dc_00000 internal

LINSTOR ==> r l
┊ pvc-321752d7-2ffb-4972-b585-7f0823fd31dc ┊ embassy-k8dev-node-1 ┊ 7000 ┊ InUse  ┊ Ok    ┊ UpToDate ┊ 2021-11-10 15:03:36 ┊
```
Afterwards the pvc will start working again without any problems. Unfortunately this fix is not permanent and after the satellite on the node is restarted or the system is rebooted the pvc reverts to a diskless state.

Ist it possible to permanently attach the devices back to the corresponding resources / update the resource definition?

Creating new pvc works without problems.

**Comment by WanzenBug** [comment]
That is very strange. Maybe DRBD 8.4 was loaded by mistake, which would refuse to attach the given resource? But then the attach later would also fail.

You can try `linstor r toggle-disk ...` to make the attachment permanent. LINSTOR should then just attach the existing volumes.

**Comment by WanzenBug** [comment]
> Would specifying the correct storage pool with the preexisting device in the toggle-disk command result in the existing device being attached or in a new one being created

Yes, thats what should happen.

The error you are seeing looks kind of familiar. Maybe you first need to `linstor rg m -l DRBD,STORAGE <rgname>`. The RG name should be set in your storage class (or one was generated, in which case you need to check `linstor rg l`.

Then try `linstor r toggle-disk --storage-pool <pool> ...` again.

**Comment by tauu** [comment]
Thanks for the detailed information! So I checked the resource group and it uses the layers you have mentioned in the modify command.
```
LINSTOR ==> rd l
┊ pvc-321752d7-2ffb-4972-b585-7f0823fd31dc ┊ 7000 ┊ csi-a524f95a-37ec-42fa-8b76-806c1e093fe9 ┊ ok    ┊
LINSTOR ==> rg l
┊ csi-a524f95a-37ec-42fa-8b76-806c1e093fe9 ┊ PlaceCount: 1                   ┊ 0      ┊             ┊
┊                                          ┊ StoragePool(s): lvm-thin        ┊        ┊             ┊
┊                                          ┊ LayerStack: ['DRBD', 'STORAGE'] ┊        ┊             ┊
```
The modify command has ben run nevertheless and did not cause any issues. Setting the storage pool in the toggle-disk command afterwards yields the same error message as before unfortunately. :(
```
LINSTOR ==> r toggle-disk --storage-pool lvm-thin node-1 pvc-321752d7-2ffb-4972-b585-7f0823fd31dc

Class canonical name:               com.linbit.ImplementationError
Generated at:                       Method 'ensureStackDataExists', Source file 'CtrlRscLayerDataFactory.java', Line #165

Error message:                      Cannot create resource with empty layer list
```
If the layers, the error message is referring to, should be the ones in the layer stack, I wonder why the error messages indicates the list would be empty.

Could manually alter the pvc-321752d7-2ffb-4972-b585-7f0823fd31dc.res file in `/var/lib/linstor.d` and executing the toggle-disk command afterwards resolve the issue?

**Comment by WanzenBug** [comment]
No, LINSTOR would rewrite the resource file. One thing you can try: delete one of the diskless resources, and re-add it `linstor r c <node> <rsc> --storage-pool lvm-thin -l DRBD,STORAGE`. That should bypass whatever else linstor thinks the resource should be.

Since the original is diskless, it won't remove the existing backing volume, and once re-created it will "find" it again. At least thats how it should work. Better only try this one by one :wink:

**Comment by tauu** [comment]
Sorry for responding a bit late, but I had to wait until it was ok to remove the resources and risk them not being available if something goes wrong. But in fact the commands you proposed work as described. The recreated resources magically found the drives and work without issues now. Rebooting the node also does not break the resources, so hopefully all is good now. :)

Thanks a lot for the help!
