### ISSUE TITLE
Storage pools are not getting created - v1.7.0-rc.1

### ISSUE THREAD

**Issue by sribee** [piraeusdatastore/piraeus-operator#239]
Storage pools are not getting created consistently with v1.7.0-rc.1. Only few nodes are configured, and others are configured after reapplying LinstorSatelliteSet configuration. Seems like some timing issue.

$ cat linstor-storage-pools.yaml
operator:
  satelliteSet:
    storagePools:
      lvmThinPools:
      - name: linstor_pool
        thinVolume: lvm_linstor
        volumeGroup: vg_linstor

Installed operator using 'helm install -f linstor-storage-pools.yaml charts/piraeus-op'
Storage pool is created only on one node.
root@piraeus-op-cs-controller-5598b95cfd-wh7jn:/# linstor sp l
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ StoragePool          ┊ Node         ┊ Driver   ┊ PoolName               ┊ FreeCapacity ┊ TotalCapacity ┊ CanSnapshots ┊ State ┊ SharedName ┊
╞════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ DfltDisklessStorPool ┊ node-agent00 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent01 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent02 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent10 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent11 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent12 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent20 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent21 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent22 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ linstor_pool         ┊ node-agent11 ┊ LVM_THIN ┊ vg_linstor/lvm_linstor ┊   249.75 GiB ┊    249.75 GiB ┊ True         ┊ Ok    ┊            ┊
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Pools are configured on all nodes after editing the LinstorSatelliteSet config
kubectl edit LinstorSatelliteSet.piraeus.linbit.com 
root@piraeus-op-cs-controller-5598b95cfd-wh7jn:/# linstor sp l
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ StoragePool          ┊ Node         ┊ Driver   ┊ PoolName               ┊ FreeCapacity ┊ TotalCapacity ┊ CanSnapshots ┊ State ┊ SharedName ┊
╞════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ DfltDisklessStorPool ┊ node-agent00 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent01 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent02 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent10 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent11 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent12 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent20 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent21 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent22 ┊ DISKLESS ┊                        ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ linstor_pool         ┊ node-agent00 ┊ LVM_THIN ┊ vg_linstor/lvm_linstor ┊   249.75 GiB ┊    249.75 GiB ┊ True         ┊ Ok    ┊            ┊
┊ linstor_pool         ┊ node-agent01 ┊ LVM_THIN ┊ vg_linstor/lvm_linstor ┊   249.75 GiB ┊    249.75 GiB ┊ True         ┊ Ok    ┊            ┊
┊ linstor_pool         ┊ node-agent02 ┊ LVM_THIN ┊ vg_linstor/lvm_linstor ┊   249.75 GiB ┊    249.75 GiB ┊ True         ┊ Ok    ┊            ┊
┊ linstor_pool         ┊ node-agent10 ┊ LVM_THIN ┊ vg_linstor/lvm_linstor ┊   249.75 GiB ┊    249.75 GiB ┊ True         ┊ Ok    ┊            ┊
┊ linstor_pool         ┊ node-agent11 ┊ LVM_THIN ┊ vg_linstor/lvm_linstor ┊   249.75 GiB ┊    249.75 GiB ┊ True         ┊ Ok    ┊            ┊
┊ linstor_pool         ┊ node-agent12 ┊ LVM_THIN ┊ vg_linstor/lvm_linstor ┊   249.75 GiB ┊    249.75 GiB ┊ True         ┊ Ok    ┊            ┊
┊ linstor_pool         ┊ node-agent20 ┊ LVM_THIN ┊ vg_linstor/lvm_linstor ┊   249.75 GiB ┊    249.75 GiB ┊ True         ┊ Ok    ┊            ┊
┊ linstor_pool         ┊ node-agent21 ┊ LVM_THIN ┊ vg_linstor/lvm_linstor ┊   249.75 GiB ┊    249.75 GiB ┊ True         ┊ Ok    ┊            ┊
┊ linstor_pool         ┊ node-agent22 ┊ LVM_THIN ┊ vg_linstor/lvm_linstor ┊   249.75 GiB ┊    249.75 GiB ┊ True         ┊ Ok    ┊            ┊
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by WanzenBug** [comment]
How long did you wait before editing the satellite set? There should be a timer that retries reconciling the satellite set every minute. Would it be possible to share your operator logs?

**Comment by sribee** [comment]
I waited probably around 30 min, I even tried restarting the satellites, that didn't work. Only when the config is reapplied, the pools were created. Unfortunately,  I don't have the setup right anymore, will re-try and post the logs.

**Comment by sribee** [comment]
Please see the attached operator log file. This time, storage pools are not created even after editing the satellite set.

root@piraeus-op-cs-controller-5598b95cfd-s46v9:/# linstor sp l
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ StoragePool          ┊ Node         ┊ Driver   ┊ PoolName ┊ FreeCapacity ┊ TotalCapacity ┊ CanSnapshots ┊ State ┊ SharedName ┊
╞══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ DfltDisklessStorPool ┊ node-agent00 ┊ DISKLESS ┊          ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent01 ┊ DISKLESS ┊          ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent10 ┊ DISKLESS ┊          ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent11 ┊ DISKLESS ┊          ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent12 ┊ DISKLESS ┊          ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent20 ┊ DISKLESS ┊          ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent21 ┊ DISKLESS ┊          ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node-agent22 ┊ DISKLESS ┊          ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[operator.log](https://github.com/piraeusdatastore/piraeus-operator/files/7553485/operator.log)

**Comment by WanzenBug** [comment]
Seems the operator gets stuck while adding the node labels. This might be related to the known issue surrounding the `MASTER_PASSPHRASE`. There is a bug in LINSTOR 1.16.0 which might trigger when you have the `MASTER_PASSPHRASE` environment variable set on startuup: the controller will not be able to communicate with the satellites, even tough they are reported online. all LINSTOR commands will time out and you just get an error report (check `linstor err l`) with a "node not authorized message". Do you see such an error?

If so, please try `kubectl rollout restart daemonset/piraeus-op-ns-node`, that should get LINSTOR unstuck.

**Comment by sribee** [comment]
I didn't see any errors, linstor commands seem to be working fine. Also, I tried the kubectl rollout, that also didn't help.

root@piraeus-op-cs-controller-5598b95cfd-s46v9:/# linstor n l
╭──────────────────────────────────────────────────────────────────────────────────────────────╮
┊ Node                                      ┊ NodeType   ┊ Addresses                  ┊ State  ┊
╞══════════════════════════════════════════════════════════════════════════════════════════════╡
┊ node-agent00                              ┊ SATELLITE  ┊ 172.16.20.106:3366 (PLAIN) ┊ Online ┊
┊ node-agent01                              ┊ SATELLITE  ┊ 172.16.22.252:3366 (PLAIN) ┊ Online ┊
┊ node-agent10                              ┊ SATELLITE  ┊ 172.16.22.90:3366 (PLAIN)  ┊ Online ┊
┊ node-agent11                              ┊ SATELLITE  ┊ 172.16.20.55:3366 (PLAIN)  ┊ Online ┊
┊ node-agent12                              ┊ SATELLITE  ┊ 172.16.21.250:3366 (PLAIN) ┊ Online ┊
┊ node-agent20                              ┊ SATELLITE  ┊ 172.16.22.146:3366 (PLAIN) ┊ Online ┊
┊ node-agent21                              ┊ SATELLITE  ┊ 172.16.20.116:3366 (PLAIN) ┊ Online ┊
┊ node-agent22                              ┊ SATELLITE  ┊ 172.16.21.142:3366 (PLAIN) ┊ Online ┊
┊ piraeus-op-cs-controller-5598b95cfd-s46v9 ┊ CONTROLLER ┊ 10.200.50.131:3366 (PLAIN) ┊ Online ┊
╰──────────────────────────────────────────────────────────────────────────────────────────────╯
root@piraeus-op-cs-controller-5598b95cfd-s46v9:/# linstor v l
╭──────────────────────────────────────────────────────────────────────────────────────────╮
┊ Node ┊ Resource ┊ StoragePool ┊ VolNr ┊ MinorNr ┊ DeviceName ┊ Allocated ┊ InUse ┊ State ┊
╞══════════════════════════════════════════════════════════════════════════════════════════╡
╰──────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by WanzenBug** [comment]
I'm a bit at a loss right now. Looking at the logs, I can see that we reach this line:
https://github.com/piraeusdatastore/piraeus-operator/blob/91f5ac3fffdf835aaf1cea34c08b380c2482a447/pkg/controller/linstorsatelliteset/linstorsatelliteset_controller.go#L485

but not this line:
https://github.com/piraeusdatastore/piraeus-operator/blob/91f5ac3fffdf835aaf1cea34c08b380c2482a447/pkg/controller/linstorsatelliteset/linstorsatelliteset_controller.go#L492

Stepping throught the methods in between, we at least reach this request:
```
https://github.com/piraeusdatastore/piraeus-operator/blob/91f5ac3fffdf835aaf1cea34c08b380c2482a447/pkg/linstor/client/client.go#L169
```

But I can't tell if it completed sucessfully. I also can't tell what happens afterwards. At some point we should get our context cancelled, but that does not seem to happen for some reason :/

**Comment by WanzenBug** [comment]
Oh, I see it now. The change in #235 deadlocks the satellite reconciliation :/

```go
func main() {
	errs := make(chan error)

	wg := sync.WaitGroup{}

	wg.Add(1)

	go func() {
		defer wg.Done()
		errs <- nil
	}()

	wg.Wait()
	close(errs)

	for err := range errs {
		fmt.Printf("%+v\n", err)
	}
}
```

The spawned go-routine is waiting for the channel to confirm that the item was received, the other is waiting for the wait group to be done.

**Comment by WanzenBug** [comment]
@sribee can you verify that it's working with the current master?

**Comment by sribee** [comment]
Yes, it worked with current master - thanks for quick resolution.

**Comment by WanzenBug** [comment]
Thanks for taking the time to report the issue and help test the fix :bow:
