### ISSUE TITLE
unable to create TLSSecret for HTTP client

### ISSUE THREAD

**Issue by OleksandrShtepa** [piraeusdatastore/piraeus-operator#248]
Tried to install a piraeus-operator using [security.md](https://github.com/piraeusdatastore/piraeus-operator/blob/master/doc/security.md).
The Controller can't find satelite nodes and got an error in operator logs:
> time="2021-12-23T08:03:34Z" level=warning msg="failed to update status. original errors: [unable to create TLSSecret for HTTP client: failed to fetch secret: Secret \"http-client\" not found]" Controller=linstorsatelliteset controller=LinstorSatelliteSet requestName=piraeus-op-ns requestNamespace=piraeus

There are bugs in [1](https://github.com/piraeusdatastore/piraeus-operator/blob/1da6736583155d1111e238e1800e4958073e90f5/pkg/controller/linstorsatelliteset/linstorsatelliteset_controller.go#L386), [2](https://github.com/piraeusdatastore/piraeus-operator/blob/1da6736583155d1111e238e1800e4958073e90f5/pkg/controller/linstorsatelliteset/linstorsatelliteset_controller.go#L743), [3](https://github.com/piraeusdatastore/piraeus-operator/blob/1da6736583155d1111e238e1800e4958073e90f5/pkg/controller/linstorsatelliteset/linstorsatelliteset_controller.go#L386):

`lc.NamedSecret(ctx, r.client, satelliteSet.Spec.LinstorHttpsClientSecret),`

The method NamedSecret accepts a namespace name as 3nd argument, not a secret name. So linstorsatelliteset_controller tires to get a secret **http-client** from namespace **http-client**.

LinstorController and LinstorCSIDriver did not have any problems with the Secret (name=http-client namespace=piraeus).
linstorcontroller_controller has a right [code](https://github.com/piraeusdatastore/piraeus-operator/blob/1da6736583155d1111e238e1800e4958073e90f5/pkg/controller/linstorcontroller/linstorcontroller_controller.go#L248):

`lc.NamedSecret(ctx, r.client, controllerResource.Namespace)`

I used follow helm values as a workaround:
> linstorHttpsControllerSecret: http-controller
linstorHttpsClientSecret: piraeus

Environment:
- OpenShift version 4.9.0-0.okd-2021-12-12-025847
- helm chart piraeus-1.7.0

**Comment by WanzenBug** [comment]
Thanks for the report and thorough write-up. I've open #249 to fix this issue and added you in `Reported-By` in the commit message.
