### ISSUE TITLE
Unable to ship snapshots to S3/MinIO

### ISSUE THREAD

**Issue by aureq** [piraeusdatastore/piraeus-operator#250]
Hi,

I'm trying to ship some snapshots to MinIO/S3 but this fails and I don't know where I should look in order to fix the problem.

Details:

I've deployed the operator onto a 3 nodes cluster and it works fine. I have volumes I can use and access which is also great.
I'm able to take snapshots of these volume and list them using `kubectl linstor snapshot list`. 

I was also able to create a remote using `kubectl linstor remote create s3 ...` and it show up correctly using `kubectl linstor remote list`.

However, I can't seem to be able to ship these snapshots outside the cluster when I run the command `kubectl linstor backup create --full minio pvc-8f580104-7d18-46dc-bda3-a77107ada6bc`

The command returns:
```
INFO:
    Cannot use node 'k3s-1' as it does not support the tool(s): ZSTD
INFO:
    Cannot use node 'k3s-2' as it does not support the tool(s): ZSTD
INFO:
    Cannot use node 'k3s-3' as it does not support the tool(s): ZSTD
ERROR:
    Backup shipping of resource 'pvc-8f580104-7d18-46dc-bda3-a77107ada6bc' cannot be started since there is no node available that supports backup shipping.
```

I *think* the `ZSTD` message refers to the missing command `zstd` tools for fast lossless compression algorithm. However, I can't find which component refers to it, and where it should be installed (which specific container? Node?)

Could it be possible to get some pointer to help resolve this issue please?

Thank you

Environment:
- OS: Debian 11 Bullseye
- Kubernetes 1.21.7+k3s1
- Piraeus operator provided via Chart v1.7.0

**Comment by WanzenBug** [comment]
Indeed looks like we forgot to include the right dependencies for backups.

Dockerfile live here: https://github.com/piraeusdatastore/piraeus/tree/master/dockerfiles/piraeus-server

Maybe just adding `zstd` to the apt-get install line is enough. I will have to try.

**Comment by aureq** [comment]
@WanzenBug yes, I updated the image and included `zstd` and the error message was gone.
