### ISSUE TITLE
OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/linstor-wait-until": stat /linstor-wait-until: no such file or directory: unknown

### ISSUE THREAD

**Issue by tobg** [piraeusdatastore/piraeus-operator#278]
Since this morning the csi controller and few of the csi node pods are in error state. This is the error:
 OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/linstor-wait-until": stat /linstor-wait-until: no such file or directory: unknown

 Normal   Created    12s (x2 over 13s)  kubelet            Created container linstor-wait-api-online
  Warning  Failed     12s (x2 over 13s)  kubelet            Error: failed to start container "linstor-wait-api-online": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/linstor-wait-until": stat /linstor-wait-until: no such file or directory: unknown

After I restart a running csi node pod we got the same error.

We using piraeus-operator 1.7.1

**Comment by WanzenBug** [comment]
> We using piraeus-operator 1.7.1

That looks more like using the latest operator from master. The dependence on the `linstor-wait-until` binary was just added recently: https://github.com/piraeusdatastore/piraeus-operator/pull/275

In theory (and from just checking, also in practice), when we create a release we set the default operator image to the tagged version, i.e. `quay.io/piraeusdatastore/piraeus-operator:v1.7.1`, but then switch it back to `quay.io/piraeusdatastore/piraeus-operator:latest`, which makes it easier for us to develop.

So you somehow ended up with the latest operator version. To fix this, `kubectl edit deployment piraeus-op-operator` and set the image to the tagged version matching your release.

**Comment by tobg** [comment]
Thank you very much. Indeed our helm values was set to latest for the operator. Fixed the issue by set it to v1.7.1

**Comment by tobg** [comment]
Fixed, see above.
