### ISSUE TITLE
CS-Controller unable to start, when TLS enabled

### ISSUE THREAD

**Issue by catsem** [piraeusdatastore/piraeus-operator#283]
Hey,
I tried to enable TLS for the piraeus components "the manual way" as described in https://github.com/piraeusdatastore/piraeus-operator/blob/v1.8.0-rc.1/doc/security.md 

I'm using v1.8.0-rc1 where the certificate handling has been changed to pem instead of java key stores.

Snipped from a cs-controllers pod log:
[..]
Importing keystore /tmp/tmp.ilegNW0b9e to /etc/linstor/ssl/keystore.jks...
keytool error: java.lang.NullPointerException: invalid null input
keytool error: java.lang.Exception: Certificate not imported, alias <ca> already exists
Existing entry alias linstor exists, overwrite? [no]:  Enter new alias name     (RETURN to cancel import for this entry):  Importing keystore /tmp/tmp.ZagFjyriME to /etc/linstor/https/keystore.jks...
keytool error: java.lang.NullPointerException: invalid null input
keytool error: java.lang.Exception: Certificate not imported, alias <ca> already exists
LINSTOR, Module Controller
Version:            1.18.0-rc.3 (3db327012f2c488047e2a0eaf56d0ff6e26cc301)
Build time:         2022-02-23T09:06:50+00:00
Java Version:       11
Java VM:            Debian, Version 11.0.14+9-post-Debian-1deb11u1
Operating system:   Linux, Version 5.4.0-100-generic
Environment:        amd64, 1 processors, 3843 MiB memory reserved for allocations

System components initialization in progress
[..]

Greetings
Christian

**Comment by WanzenBug** [comment]
@kvaps does this look like what you are trying to fix in https://github.com/piraeusdatastore/piraeus/pull/101 ?

**Comment by WanzenBug** [comment]
I think it's only empty if you start a new pod. If a pod restarts, for example because the leader-election timed out, then the emptyDir will still have the original content. 

But I'm also not sure why that is even an issue, I assume the cert/key is then just not loaded and then the "existing" cert/key is used. But that shouldn't impact the start of the controller...

**Comment by kvaps** [comment]
Yeah, in some cases emptyDir really can be not empty. Probably it is intended behavior
https://github.com/kubernetes/kubernetes/issues/53423

**Comment by catsem** [comment]
Great the issue is resolved! Thanks for the fast solution!

Unfortunately I'm still unable to start the controllers. They seem to be unable to reach the etcd over the tls connection:
10:27:14.754 [Main] ERROR LINSTOR/Controller - SYSTEM - Database initialization error [Report number 622B2400-00000-000000]
But I guess thats another story.
