### ISSUE TITLE
Don't use `:latest` tag

### ISSUE THREAD

**Issue by kvaps** [piraeusdatastore/piraeus-operator#286]
The version of piraeus-operator must be set and updated together with the helm chart itself.
https://github.com/piraeusdatastore/piraeus-operator/blob/52eb3454f0036e50694b5e5c4378e25d3907f26c/charts/piraeus/values.yaml#L58

Otherwise you have risk on running old operator version with new helm-chart, which is obviously will not work:

```
NAME                                        READY   STATUS                       RESTARTS   AGE
piraeus-op-cs-controller-66b5755df4-6pn8f   1/1     Running                      0          118s
piraeus-op-csi-node-6skmf                   1/3     CreateContainerConfigError   0          118s
piraeus-op-csi-node-plzz5                   1/3     CreateContainerConfigError   0          118s
piraeus-op-csi-node-vtzp4                   1/3     CreateContainerConfigError   0          118s
piraeus-op-ha-controller-5fddf79c88-47tvg   0/1     Init:0/1                     0          2m30s
piraeus-op-ns-node-62fwl                    1/2     CrashLoopBackOff             4          118s
piraeus-op-ns-node-9lqrw                    1/2     Error                        4          118s
piraeus-op-ns-node-ch2bf                    1/2     Error                        4          118s
piraeus-op-operator-fb58bb6b8-fmhrx         1/1     Running                      0          2m30s
```

**Comment by WanzenBug** [comment]
FYI: It's currently `latest` while developing, every release should use the actual release tag. It's not ideal, but there is no simple way to _always_ sync the chart with the right tag. An alternative would be to keep the old operator tag during development, which might also fail (but maybe less often?)

**Comment by kvaps** [comment]
It can also be solved to `imagePullPolicy: Always`, but I think it's better to keep the latest release tag
