### ISSUE TITLE
DivceName is None and no known workaround works

### ISSUE THREAD

**Issue by tobg** [piraeusdatastore/piraeus-operator#287]
With Operator 1.7.1 and 1.8.0 we have DeviceName None for linstor v l

- Restart Node (several times) does not work
- Restart NS Controller does not work
- linstor reconnect node does not work
- lvscan shows device/resource as active

It affects only one node.

![image](https://user-images.githubusercontent.com/49125745/159159218-cd764327-3e17-4b04-b595-3500535bac3d.png)

**Comment by WanzenBug** [comment]
Can you check the LINSTOR error reports -> `linstor err l`. If I had to guess there is probably something about some DRBD command timing out. You could also just create a linstor sos report, which includes the whole cluster state + error reports for us to anaylze:

```
$ kubectl exec deployment/piraeus-op-cs-controller -- linstor sos-report create
SUCCESS:
    SOS Report created on Controller: /var/log/linstor-controller/sos_2022-03-21_08-27-38.tar.gz
$ kubectl cp <piraeus-cs-controller-pod>:/var/log/linstor-controller/sos_2022-03-21_08-27-38.tar.gz sos_report.tar.gz
```

**Comment by WanzenBug** [comment]
Seems very strange to me. The issue I could find is that on node `digoc.tobg.services` LINSTOR does not configure volumes for _some_ drbd resources. I'm note sure how this could happen. Please open an issue with the SOS report upstream https://github.com/linbit/linstor-server

**Comment by tobg** [comment]
Thanks, did open a new issue at linstor-server

**Comment by tobg** [comment]
Works now since operator version 1.8.1
