### ISSUE TITLE
Cannot create new pvc. Got autoplace error

### ISSUE THREAD

**Issue by tobg** [piraeusdatastore/piraeus-operator#292]
This is the error:

Events:
  Type     Reason                Age                From                                                                                                   Message
  ----     ------                ----               ----                                                                                                   -------
  Warning  ProvisioningFailed    41s                linstor.csi.linbit.com_piraeus-op-csi-controller-5b78f8559-n5hg9_d49b82e6-0617-4443-aad4-66b5555eb513  failed to provision volume with StorageClass "linstor-sc-std-ha-new": rpc error: code = Internal desc = CreateVolume failed for pvc-20ac6d99-2d8a-45ba-ab3d-360e6536f36c: failed to autoplace constraint replicas: Message: 'Successfully set property key(s): StorPoolName' next error: Message: 'Resource 'pvc-20ac6d99-2d8a-45ba-ab3d-360e6536f36c' successfully autoplaced on 1 nodes'; Details: 'Used nodes (storage pool name): 'k8smaster.tobg.services (lvm-std-ha)'' next error: Message: 'Updated DRBD auto verify algorithm to 'crct10dif-pclmul'' next error: Message: 'Created resource 'pvc-20ac6d99-2d8a-45ba-ab3d-360e6536f36c' on 'k8smaster.tobg.services'' next error: Message: 'Added peer(s) 'k8smaster.tobg.services' to resource 'pvc-20ac6d99-2d8a-45ba-ab3d-360e6536f36c' on 'digoc.tobg.services'' next error: Message: 'Resource did not become ready on node 'k8smaster.tobg.services' within reasonable time, check Satellite for errors.'
  Normal   Provisioning          40s (x2 over 98s)  linstor.csi.linbit.com_piraeus-op-csi-controller-5b78f8559-n5hg9_d49b82e6-0617-4443-aad4-66b5555eb513  External provisioner is provisioning volume for claim "default/hdd-pvc-lndbig-new-bkp"
  Normal   ExternalProvisioning  6s (x8 over 98s)   persistentvolume-controller                                                                            waiting for a volume to be created, either by external provisioner "linstor.csi.linbit.com" or manually created by system administrator.
  
  
This is happen with every node if autoplace is at least 2. Autoplce 1 works flawlessly
PVC creation for single nodes works just fine.

ERROR:
    Resource did not become ready on node 'k8smaster.tobg.services' within reasonable time, check Satellite for errors.

Satelite log:
19:16:08.104 [MainWorkerPool-1] INFO  LINSTOR/Satellite - SYSTEM - Resource 'pvc-d7420b99-1f34-4ff8-a319-955520d4bcda' created for node 'digoc.tobg.services'.
19:16:08.104 [MainWorkerPool-1] INFO  LINSTOR/Satellite - SYSTEM - Resource 'pvc-d7420b99-1f34-4ff8-a319-955520d4bcda' created for node 'k8smaster.tobg.services'.
19:16:59.041 [MainWorkerPool-1] INFO  LINSTOR/Satellite - SYSTEM - Storage pool 'lvm-std-ha' updated.

This is from linstor v l:

| digoc.tobg.services     | pvc-8047a4f5-c6e7-4c82-9455-ffef449f780d | lvm-std-ha           |     0 |    1339 | /dev/drbd1339 | 563.34 MiB | Unused |   UpToDate |
| k8smaster.tobg.services | pvc-8047a4f5-c6e7-4c82-9455-ffef449f780d | lvm-std-ha           |     0 |    1339 | /dev/drbd1339 |    839 KiB | Unused |   UpToDate |

It is in red uptodate status.

**Comment by tobg** [comment]
This is from linstor v l:


digoc.tobg.services     ┊ pvc-dc1c9871-416b-4288-bb6d-e662b152a824 ┊ lvm-std-ha           ┊     0 ┊    1397 ┊ /dev/drbd1397 ┊            ┊ Unused ┊      Error ┊
┊ k8smaster.tobg.services ┊ pvc-dc1c9871-416b-4288-bb6d-e662b152a824 ┊ lvm-std-ha           ┊     0 ┊    1397 ┊ /dev/drbd1397 ┊     -1 KiB ┊ Unused ┊    Unknown

**Comment by WanzenBug** [comment]
Check the output of `linstor sp l`, are all the nodes configured with the right storage pool, and do they report an OK status?

You can also check the kernel log on the nodes, check if DRBD reports any issues

**Comment by tobg** [comment]
Works now since operator 1.8.1
