### ISSUE TITLE
Toml values should be enclosed in double quotes

### ISSUE THREAD

**Issue by bc185174** [piraeusdatastore/piraeus-operator#309]
Hi - I have been using golang (along with the kubernetes client) to extract data from the linstor toml stored in configmaps. The toml config parsers such as Viper or go-toml requires string values to be enclosed in double quotes. For instance the `piraeus-ns-node-config` map should match:

```yaml
apiVersion: v1
data:
  linstor-client.conf: |+
    [global]
    controllers = "https://endpoint:<port>"
    cafile      = "/etc/linstor/client/"
    certfile    = "/etc/linstor/client/"
    keyfile     = "/etc/linstor/client/"

  linstor_satellite.toml: |
    [netcom]
      type = ""
      port = <port-number-integer>
      server_certificate = ""
      key_password = ""
      keystore_password = ""
      trusted_certificates = ""
      truststore_password = ""
      ssl_protocol = ""
```

**Comment by WanzenBug** [comment]
I think you are talking about `linstor-client.conf` specifically, right? If so: that's not a toml file. The linstor client uses python `configparser` module, so it uses whatever ini-file syntax that one uses.

**Comment by bc185174** [comment]
> I think you are talking about `linstor-client.conf` specifically, right? If so: that's not a toml file. The linstor client uses python `configparser` module, so it uses whatever ini-file syntax that one uses.

Ah thank you. Looks like Viper supports INI-style config so I will give that a try. Was there a particular reason why two different config formats are used?

**Comment by WanzenBug** [comment]
> Was there a particular reason why two different config formats are used?

I don't know the exact reason, one of the LINSTOR developers probably knows more about that, but I think the main concern was to have the client only depend on the python standard library, which does not have a toml parser by default (I think that has changed in the meantime...)
