### ISSUE TITLE
Linstor UI?

### ISSUE THREAD

**Issue by Vertiwell** [piraeusdatastore/piraeus-operator#320]
Hi,
Extra easy question, https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#_installing_the_linstor_gui mentions a built-in UI.
Is this UI something that is available on Piraeus?
Thank you.

**Comment by WanzenBug** [comment]
Hi,

UI is currently not open-source, and not available in Piraeus.

**Comment by shurkus** [comment]
https://github.com/shurkys/linstor-gui. The repository is currently incomplete and is more suitable for browsing resources rather than creating them. But some can be created.

**Comment by shurkys** [comment]
https://github.com/shurkys/linstor-gui. The repository is currently incomplete and is more suitable for browsing resources rather than creating them. But some can be created.

**Comment by maxpain** [comment]
@WanzenBug 

https://github.com/LINBIT/linstor-gui
it's now open-source

**Comment by WanzenBug** [comment]
Sure, I'll need to check if the package can be made available on https://packages.linbit.com/public/...

**Comment by WanzenBug** [comment]
See https://github.com/piraeusdatastore/piraeus/pull/195

**Comment by maxpain** [comment]
@WanzenBug When should we expect the release with this feature?
