### ISSUE TITLE
[feature-request] Automate node deletion process

### ISSUE THREAD

**Issue by kvaps** [piraeusdatastore/piraeus-operator#328]
If node removed from Kubernetes cluster it should be removed from LINSTOR

**Comment by WanzenBug** [comment]
This should already be implemented. Unless I'm mistaken, when a node is removed from k8s the DS will terminate/remove the pod, and then the operator will first evict/evacute the satellite, then completely remove it from LINSTOR.

**Comment by kvaps** [comment]
Hmm, then something has gone wrong in my cluster.
I'll check this again, reopen if this problem still persist.
