### ISSUE TITLE
Provide etcd to K8S backend migration script 

### ISSUE THREAD

**Issue by phoenix-bjoern** [piraeusdatastore/piraeus-operator#341]
Using the K8S backend (=etcd) option makes a lot of sense in many ways, so it should be the new default for the Operator v2. Removing the bundled etcd of Piraeus simplifies the storage setup and reduces the risk of failure.
However, a migration of existing installations is currently not possible. Removing all existing resources and recreate them is not a a viable option for production systems. So the way for migration is a migration script which copies all data in the Piraeus etcd to the K8S backend.

**Comment by kvaps** [comment]
I did something like that one time
https://github.com/kvaps/linstor-backup-script

**Comment by phoenix-bjoern** [comment]
@kvaps interesting, thanks for sharing. What will happen to existing DRBD resources when you restore the Linstor resources? Will they get recognized and used like before?

**Comment by kvaps** [comment]
Yes, but you need to preserve all the parameters like node_ids and so on

**Comment by kvaps** [comment]
Just updated license from gpl-3.0 to apache2 so you can freely use this code in this repo.
It's pretty old, but I think it might be useful.

I successfully migrated from h2 to postgresql two years ago, and didn't use it anymore 😅

**Comment by WanzenBug** [comment]
LINSTOR 1.24.0-rc.2 ships with an experimental DB export & import tool. With that we can work on an automatic migration for LINSTOR resources.
