### ISSUE TITLE
[Kubernetes-CRD DB] Missing ClusterRole & binding for non-Helm install

### ISSUE THREAD

**Issue by t3hmrman** [piraeusdatastore/piraeus-operator#378]
There seems to be a missing RBAC rule that enables CRD for the `linstor-controller``ServiceAccount`, when using [the Kubernetes backend feature](https://piraeus.io/site/docs/k8s-backend):

- [`deploy/piraeus/templates/controller-rbac.yaml` only contains the leader election role + binding](https://github.com/piraeusdatastore/piraeus-operator/blob/bc5214faad1c92839c110a23c1f23002e8214900/deploy/piraeus/templates/controller-rbac.yml)
- [`charts/piraeus/templates/controller-rbac.yaml` contains an addition role + binding for k8s resources](https://github.com/piraeusdatastore/piraeus-operator/blob/0da6741a267431e221b0059719724b455c9e7dd9/charts/piraeus/templates/controller-rbac.yml)

This makes sense since the k8s-as-DB usage is optional, but would be nice if it was in the non-Helm install and maybe commented out or included by default just-in-case.

Here's the error report, if it helps (was very helpful in tracking down the issue, so that was great):

[linstor-ErrorReport-63B39B60-00000-000000.log](https://github.com/piraeusdatastore/piraeus-operator/files/10334187/linstor-ErrorReport-63B39B60-00000-000000.log)

**Comment by WanzenBug** [comment]
Makes sense, as the deploy resources are created by running `helm template ...` with the default settings. And since we currently do not have an easy migration path from the old Etcd deployment to the K8s DB, I'm not sure how to fix this.

Perhaps a separate `deploy/piraeus-k8s-db` directory?

**Comment by t3hmrman** [comment]
Maybe simply mentioning it in the non-helm instructions prominently is enough? I did take a look through that and I assume if I'd seen it there I wouldn't have been surprised.

Just about everything else went smoothly, despite me going through and doing lots of renaming/tinkering, IIRC that was the only big change.

**Comment by WanzenBug** [comment]
Operator v2 no longer supports the etcd backend, so uses k8s by default.
