### ISSUE TITLE
Support init containers or gracefully handle already mounted devices in GKE

### ISSUE THREAD

**Issue by inviscid** [piraeusdatastore/piraeus-operator#388]
We are facing an issue with GKE nodes when trying to use Piraeus with the local SSD drives.  GKE automatically mounts the local SSD drives and there is no way to disable this.  I would imagine this is not just a GKE specific problem in environments where you can't tightly control the startup condition of a K8s node.

For example, this would be a typical startup condition for a node:

```
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    0  100G  0 disk 
|-sda1    8:1    0 99.9G  0 part /
|-sda14   8:14   0    4M  0 part 
`-sda15   8:15   0  106M  0 part /boot/efi
sdb       8:16   0  375G  0 disk /mnt/disks/ssd0
```

We could create a daemonset to take care of the `umount` and `wipefs` process but it could end up in a race condition with the Piraeus daemonset that is trying to configure the devices specified in the `devicePaths`.

Ideally, Piraeus would handle this transparently by unmounting and wiping any devices included in the `devicePaths` parameter so they can be used.  However, if this is outside the scope of what you want Piraeus to do, could you allow the specification of an init container that can perform this task.  Currently, the operator spec seems limited to specifying side cars only.

The other node prep action that needs to be performed is adding the `multipathd` blacklist entry on the node.  Again, this could be accomplished using an daemonset but the race condition risk is still present.

```
blacklist {
        devnode "^drbd[0-9]+"
}
```

I did see [this option](https://github.com/piraeusdatastore/piraeus-operator/issues/289#issuecomment-1194019765) to configure the volume groups ahead of time and then specify the volume group rather than the `devicePaths`.  Not sure if that is the most elegant solution to a relatively simple issue of dealing with unmounting the specified devices.

Of course, also open to a different approach that is commonly used to overcome this issue.

**Comment by inviscid** [comment]
An update...

I followed the process of setting up the nodes using a daemonset that creates the volume group of the local SSDs.  I then updated the Piraeus deployment to use the `volumeGroup` specification rather than `devicePaths`.  After a number of false starts it finally was able to recognize the groups and thin logical volumes for use.

I'm not the best at writing shell scripts so there is probably a more elegant way to do this.  For reference, this is the script that the daemonset runs:

```
#!/usr/bin/env bash
set -euo pipefail
set -x

# Prepare the DRDB aspect by adding a blacklist entry
mkdir -p /etc/multipath/conf.d/
blacklist_stanza='blacklist {devnode "^drbd[0-9]+"}'
echo $blacklist_stanza > /etc/multipath/conf.d/drbd.conf

# https://cloud.google.com/compute/docs/disks/performance#optimize_local_ssd

# unmount all local SSD disks
if old_mounts=$(findmnt -n -a -l --nofsroot | grep /mnt/disks/ssd) ; then
  echo "$old_mounts" | awk '{print $1}' | while read -r ssd ; do
    umount "$ssd"
    new_fstab=$(grep -v "$ssd" /etc/fstab) || echo "fstab is now empty"
    echo "$new_fstab" > /etc/fstab
  done
fi

devs=$(echo "$old_mounts" | awk '{print $2}')

# If LVM is already in use, this may have been re-deployed.
# Don't try to change the disks.
pvs=$((test -x /sbin/pvs && /sbin/pvs) || echo "")

# Create the LVM Physical Volumes (PV)
# Note that they need to be wiped first since the pvcreate command won't work on drives with data
if ! echo "$pvs" | grep vg_local_ssds ; then
  echo "$devs" | xargs /sbin/wipefs --all
  echo "$devs" | xargs /sbin/pvcreate
fi

# Show the PVs were created
/sbin/pvdisplay

# Group the PVs into an LVM volume group
if ! /sbin/vgs | grep vg_local_ssds ; then
  echo "$devs" | xargs /sbin/vgcreate vg_local_ssds
fi

# Show the VG created
/sbin/vgdisplay

# Lastly, create a logical volume to use for thin provisioning
if ! /sbin/lvs | grep thinpool ; then
  /sbin/lvcreate -l 100%FREE --thinpool thinpool --zero n vg_local_ssds
fi

# Show the logical volume created
/sbin/lvdisplay
```

**Comment by WanzenBug** [comment]
Ideally, this would be documented in a how-to guide somewhere.
