### ISSUE TITLE
Select a specific node to install storagePool

### ISSUE THREAD

**Issue by jwcfree** [piraeusdatastore/piraeus-operator#389]
Hey guys! Please help me with the my question about storagePool.

I need to select only 3 node (e.g. 3 master node's k8s) for linstor cluster. Where I need to edit that to do this?

**Comment by WanzenBug** [comment]
See https://github.com/piraeusdatastore/piraeus-operator/issues/267 and https://github.com/piraeusdatastore/piraeus-operator/issues/226 for similar questions
