### ISSUE TITLE
Deleting volumes

### ISSUE THREAD

**Issue by chemicstry** [piraeusdatastore/piraeus-operator#396]
Hi, firstly, thanks for a great project, works well so far except for some hiccups installing DRBD module on Debian 11.

I noticed that deleting volumes in kubernetes does not remove the associated resources in LINSTOR. Is this intended, not yet implemented or did I miss a configuration option somewhere?

Thanks

**Comment by WanzenBug** [comment]
Deletion should work. What's the value of the `reclaimPolicy` in your storage class? If it's `Retain`, deletion of the PVC will not delete the PV or associated resources.

**Comment by WanzenBug** [comment]
> but as far as I understand this is should only affect PV deletion in relation to PVC, which is managed by kubernetes.

This would make sense, but is false. Looking at the `Retain` policy [here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain), it explicitly states that "The associated storage asset in external infrastructure ... still exists after the PV is deleted.

**Comment by WanzenBug** [comment]
A workaround could be to change the reclaimPolicy on the PVs before deletion. That should work with any storage. Perhaps this is something for kubernetes itself to look into.

**Comment by chemicstry** [comment]
> A workaround could be to change the reclaimPolicy on the PVs before deletion. That should work with any storage. Perhaps this is something for kubernetes itself to look into.

Thanks for the tip. The following command deletes volume and everything in linstor is cleaned up nicely:

`kubectl patch pv pvc-2d086a70-07a1-4c25-8871-58f41cadbd4a -p '{"spec":{"persistentVolumeReclaimPolicy":"Delete"}}'`
