### ISSUE TITLE
Feature request: Storage Pools configuration options

### ISSUE THREAD

**Issue by tbykowsk** [piraeusdatastore/piraeus-operator#4]
Please consider providing an option to configure storage pools independently on different nodes.
Currently on each node there is a `drbdpool` storage pool created, which I only need on selected nodes. On other nodes I would like to have just a diskless storage pool.

Also please consider adding a way to set specific properties for storage pools, like for example a _PrefNic_.

**Comment by JoelColledge** [comment]
I've thought about this too and I can see that it could be important. Another possibility that we will implement is the option to use linstor's `physical-storage` commands to automatically detect and configure free storage devices. Would that work in your case?

Since you have a `drbdpool`, it looks like you are using the deployment in `examples`. I would recommend using the Helm deployment instead if it works for you, since that it is more configurable. This particular case can't yet be solved with the Helm deployment, but you can at least configure the names of the storage pools that are created.

**Comment by tbykowsk** [comment]
Having an option to use linstor's `physical-storage` commands would be an added benefit, but for now I'm more interested in differentiating storage pools configurations on different kind of nodes. I will look more closely into the Helm deployment. Thanks for the advice!

**Comment by deleteriousEffect** [comment]
Hi, it's been a while, since I touched this, but you should be able to use multiple node sets for nodes with different settings. They should be able to all talk to the same controller.

In your case, have a deployment for your storage nodes and one for your diskless ones.

**Comment by JoelColledge** [comment]
It is actually possible to do this already by creating multiple LinstorNodeSet instances all connected to the same Controller. This isn't shown in the basic example in `examples`, nor can be currently be done through the Helm chart. You would have to create the instances directly, e.g. from yaml files. But this should be reasonably straightforward. Does this resolve the question as far as your current requirements go?

**Comment by tbykowsk** [comment]
Do you mean creation of a LinstorNodeSet instance like in [this example](https://github.com/piraeusdatastore/piraeus-operator/blob/master/examples/piraeus-operator-part-2.yaml#L19)? Would it be correct, if I did not provide any `storagePools` there?
I would like the operator to deploy some nodes without any storage pools, so I can add them later on using Linstor API calls. Unless, the operator provides a way to deploy nodes only with a diskless storage pool.

**Comment by JoelColledge** [comment]
Yes, it should be fine to not provide any `storagePools` and then add them later. At the moment, the operator does not remove storage pools from Linstor when they are not in the LinstorNodeSet, so you can manage them directly in Linstor. Alternatively you should be able to add them to the LinstorNodeSet `storagePools` later and let the operator register them with Linstor.

**Comment by tbykowsk** [comment]
That should work for me, I'll leave `storagePools` empty in the manifest and add them directly in Linstor along with additional properties. Thank you @JoelColledge!

**Comment by JoelColledge** [comment]
Great. Please close the issue if it works for you.
