### ISSUE TITLE
Failed to pull image "drbd-shutdown-guard"

### ISSUE THREAD

**Issue by vasyakrg** [piraeusdatastore/piraeus-operator#425]
after reboot nodes, i have its issue

Failed to pull image "drbd-shutdown-guard": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/drbd-shutdown-guard:latest": failed to resolve reference "docker.io/library/drbd-shutdown-guard:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

why docker.io/library in satellite pods ?

```
    - name: drbd-shutdown-guard
      image: drbd-shutdown-guard
```

and can i change it to quay.io/piraeusdatastore/ ?

**Comment by WanzenBug** [comment]
Seems like you are somehow missing https://github.com/piraeusdatastore/piraeus-operator/commit/97107e891f34903df72c488a19a842e78798bb18

What version of the Operator are you running? Perhaps you just need to run:
```
kubectl apply --server-side -k "https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2.0.1
```

**Comment by vasyakrg** [comment]
> Seems like you are somehow missing [97107e8](https://github.com/piraeusdatastore/piraeus-operator/commit/97107e891f34903df72c488a19a842e78798bb18)
> 
> What version of the Operator are you running? Perhaps you just need to run:
> 
> ```
> kubectl apply --server-side -k "https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2.0.1
> ```

yes! its work.
