### ISSUE TITLE
drbd-module-loader container

### ISSUE THREAD

**Issue by lysyy** [piraeusdatastore/piraeus-operator#427]
Debian 11
Need a git checkout to regenerate drbd/.drbd_git_revision
make[1]: Entering directory '/tmp/pkg/drbd-9.2.2/drbd'

    Calling toplevel makefile of kernel source tree, which I believe is in
    KDIR=/lib/modules/5.10.0-19-amd64/build

make -C /lib/modules/5.10.0-19-amd64/build   M=/tmp/pkg/drbd-9.2.2/drbd  modules
arch/x86/Makefile:147: CONFIG_X86_X32 enabled but no binutils support
make[3]: gcc-10: No such file or directory
/usr/src/linux-headers-5.10.0-19-common/Makefile:983: /usr/src/linux-headers-5.10.0-19-common/scripts/Makefile.extrawarn: No such file or directory
make[3]: *** No rule to make target '/usr/src/linux-headers-5.10.0-19-common/scripts/Makefile.extrawarn'.  Stop.
make[2]: *** [/usr/src/linux-headers-5.10.0-19-common/Makefile:185: __sub-make] Error 2
make[1]: *** [Makefile:134: kbuild] Error 2
make[1]: Leaving directory '/tmp/pkg/drbd-9.2.2/drbd'
make: *** [Makefile:126: module] Error 2

Could not find the expexted *.ko, see stderr for more details

**Comment by WanzenBug** [comment]
This is because we don't have a matching image here: https://github.com/piraeusdatastore/piraeus/tree/master/dockerfiles/drbd-driver-loader

And we don't detect any debian OS versions here: https://github.com/piraeusdatastore/piraeus-operator/blob/v2/config/manager/default_images.yaml#L34

To give some insight: LINBIT does not officially support DRBD 9 on Debian, so it will remain untested.

**Comment by clrxbl** [comment]
> This is because we don't have a matching image here: [piraeusdatastore/piraeus@`master`/dockerfiles/drbd-driver-loader](https://github.com/piraeusdatastore/piraeus/tree/master/dockerfiles/drbd-driver-loader?rgh-link-date=2023-03-13T12%3A48%3A27Z)
> 
> And we don't detect any debian OS versions here: [`v2`/config/manager/default_images.yaml#L34](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/config/manager/default_images.yaml?rgh-link-date=2023-03-13T12%3A48%3A27Z#L34)
> 
> To give some insight: LINBIT does not officially support DRBD 9 on Debian, so it will remain untested.

https://linbit.com/drbd-user-guide/drbd-guide-9_0-en/ does mention supporting Debian 11 though?

**Comment by WanzenBug** [comment]
My mistake, then. Then we just need somebody to create the right dockerfile and update the image config.

**Comment by WanzenBug** [comment]
Implemented in #444 , improved in #472
