### ISSUE TITLE
Problem with take all nodes online with or withiout ssl

### ISSUE THREAD

**Issue by lysyy** [piraeusdatastore/piraeus-operator#435]
1. After deploy:
kubectl exec -n piraeus-datastore deploy/linstor-controller -- linstor node list
+----------------------------------------------------------------------------------------+
| Node                                | NodeType   | Addresses                 | State   |
|========================================================================================|
| k02                                 | SATELLITE  | 10.111.6.253:3366 (PLAIN) | Online  |
| k03                                 | SATELLITE  | 10.111.2.180:3366 (PLAIN) | Online  |
| k04                                 | SATELLITE  | 10.111.4.97:3366 (PLAIN)  | Online  |
| k05                                 | SATELLITE  | 10.111.3.102:3366 (PLAIN) | Online  |
| k06                                 | SATELLITE  | 10.111.5.156:3366 (PLAIN) | Online  |
| linstor-controller-6747b79648-7jx54 | CONTROLLER | 10.111.2.207:3367 (SSL)   | OFFLINE |
+----------------------------------------------------------------------------------------+

2. Try to enable ssl follow this https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/how-to/api-tls.md
I have all nodes offline (disable-back to 1). Cert tested by function k8s_secret_trusted_by() and all ok.
+--------------------------------------------------------------------------------------+
| Node                                | NodeType   | Addresses               | State   |
|======================================================================================|
| k02                                 | SATELLITE  | 10.111.6.4:3367 (SSL)   | OFFLINE |
| k03                                 | SATELLITE  | 10.111.2.165:3367 (SSL) | OFFLINE |
| k04                                 | SATELLITE  | 10.111.4.99:3367 (SSL)  | OFFLINE |
| k05                                 | SATELLITE  | 10.71.5.25:3367 (SSL)   | OFFLINE |
| k06                                 | SATELLITE  | 10.111.5.4:3367 (SSL)   | OFFLINE |
| linstor-controller-6747b79648-7jx54 | CONTROLLER | 10.111.2.207:3367 (SSL) | OFFLINE |
+--------------------------------------------------------------------------------------+

**Comment by WanzenBug** [comment]
Where does the controller actually come from? Because it's not something we register in operator v2. You can just manually remove the controller, the information is purely visual, LINSTOR does not actually need to register the Controller:
```
kubectl exec deployment/linstor-controller -- linstor node delete linstor-controller-6747b79648-7jx54
```

As for removing the NetworkPolicy, this patch should remove it completely:
```
 patches:
    - target:
        kind: NetworkPolicy
        name: satellite
      patch: |-
        - op: remove
          path: /
```

**Comment by WanzenBug** [comment]
Ok, that would explain it. I guess it's just a left-over in the database, so you can delete it without issue.

**Comment by lysyy** [comment]
Hello! I'm trying to deploy piraeus operator in another cluster, after applying
`---
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec:
  apiTLS:
    certManager:
      kind: Issuer
      name: linstor-api-ca
  internalTLS:
    certManager:
      name: linstor-internal-ca
      kind: Issuer
  patches:
    - target:
        kind: Service
        name: linstor-controller
      patch: |-
        apiVersion: v1
        kind: service
        metadata:
          name: linstor-controller
        spec:
          ipFamilyPolicy: SingleStack
    - target:
        kind: NetworkPolicy
        name: satellite
      patch: |-
        - op: remove
          path: /
    - target:
        kind: Deployment
        name: linstor-controller
      patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: linstor-controller
        spec:
          template:
            spec:
              tolerations:
                - key: node-role.kubernetes.io/control-plane
                  effect: NoSchedule
                - key: node-role.kubernetes.io/master
                  effect: NoSchedule`

i have error in operator logs, and no more resources created
2023-03-22T11:20:00Z    ERROR   Reconciler error        {"controller": "linstorcluster", "controllerGroup": "piraeus.io", "controllerKind": "LinstorCluster", "LinstorCluster": {"name":"linstorcluster"}, "namespace": "", "name": "linstorcluster", "reconcileID": "d5c42a34-c634-4142-99e9-7b32105a07d7", "error": "error in remove for path: '/': Unable to remove nonexistent key: : missing value"}
Have we another way to disable creation of network policy?

**Comment by lysyy** [comment]
Additionaly, if firstly create 
```
kubectl apply -f - <<EOF
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec: {}
EOF
```
and wait resources creation, than apply full desired manifest, network policy not removed and linstor-csi-node-* pos init failed.
Need to manualy delete network policy for working cluster.

**Comment by WanzenBug** [comment]
Try this:
```
        - op: remove
          path: /spec
```
