### ISSUE TITLE
Sattelites on dedicated nodes

### ISSUE THREAD

**Issue by lysyy** [piraeusdatastore/piraeus-operator#446]
How i can set creation rules or affinity for linstor sattelites? Like this:
```
nodeSelectorTerms:
- matchExpressions:
  key: linstor.linbit.com/piraeus-node
```
Please, give some examples. Thanks!

**Comment by WanzenBug** [comment]
See:
* [`LinstorCluster.spec.nodeSelector`](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/reference/linstorcluster.md#specnodeselector)
* [`LinstorSatelliteConfiguration.spec.nodeSelector`](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/reference/linstorsatelliteconfiguration.md#specnodeselector)
