### ISSUE TITLE
Piraeus operators connected to external linstor storage clusters

### ISSUE THREAD

**Issue by lts9527** [piraeusdatastore/piraeus-operator#447]
I have an external linstor storage cluster
Can I use piraeus-operator to connect to it
piraeus-operator is only responsible for running satellite nodes

**Comment by WanzenBug** [comment]
This is possible with Operator v1. It's not possible with Operator v2 currently. But certainly something we can support.

**Comment by lts9527** [comment]
> 这可以通过 Operator v1 实现。目前 Operator v2 是不可能的。但肯定是我们可以支持的事情。

Thank you very much for your reply, which helped me a lot
I did implement using v1
I spent a lot of time in v2
