### ISSUE TITLE
Got 401 while creating LinstorCluster: piraeusdatastore/drbd9-bullseye not found in quay.io

### ISSUE THREAD

**Issue by kvzn** [piraeusdatastore/piraeus-operator#454]
![image](https://user-images.githubusercontent.com/313271/230783551-be6a4194-3d68-4ba5-9bbd-8ffe5ea45a15.png)
![image](https://user-images.githubusercontent.com/313271/230783566-ce949595-1b6b-4661-84e5-242d926841bb.png)
![image](https://user-images.githubusercontent.com/313271/230783626-b54c3433-9a83-4bb5-aff5-8c404a78a477.png)

**Comment by WanzenBug** [comment]
Fixed in https://github.com/piraeusdatastore/piraeus/issues/140
