### ISSUE TITLE
helm chart deployment broken

### ISSUE THREAD

**Issue by jameseck** [piraeusdatastore/piraeus-operator#460]
It looks like a recent change https://github.com/piraeusdatastore/piraeus-operator/commit/5f77f51df52733f21f5d1037357b985d83d1edf9 has broken the deployment template in the helm chart.
The deployment is trying to mount a configmap volume which is not created by the helm chart.

From templates/deployment.yaml:
 59         volumeMounts:
...
 63         - mountPath: /etc/operator
 64           name: operator-config
 65           readOnly: true

 92       volumes:
...
 97       - configMap:
 98           name: {{ include "piraeus-operator.fullname" . }}-config
 99         name: operator-config

**Comment by WanzenBug** [comment]
Fixed by the last commit here: https://github.com/piraeusdatastore/piraeus-operator/pull/445
