### ISSUE TITLE
 Using the IP address as kubernetes node name can not work

### ISSUE THREAD

**Issue by little-guy-lxr** [piraeusdatastore/piraeus-operator#473]
piraeus version v2.1.0

pod can ont setup 

event:

` Warning  FailedMount  50m (x3 over 58m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[kube-api-access-lxggt data]: timed out waiting for the condition
  Warning  FailedMount  25m (x17 over 68m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data kube-api-access-lxggt]: timed out waiting for the condition
  Warning  FailedMount  5m29s (x40 over 70m)  kubelet  MountVolume.SetUp failed for volume "pvc-eb9a2879-5e15-4eaa-a425-6d49ee873e2b" : rpc error: code = Internal desc = NodePublishVolume failed for pvc-eb9a2879-5e15-4eaa-a425-6d49ee873e2b: failed to stat source device: stat : no such file or directory
`

linstor-satellite log:

`01:31:33.526 [MainWorkerPool-3] INFO  LINSTOR/Satellite - SYSTEM - Resource 'pvc-eb9a2879-5e15-4eaa-a425-6d49ee873e2b' updated for node '192.168.176.183'.
01:31:33.526 [MainWorkerPool-3] INFO  LINSTOR/Satellite - SYSTEM - Resource 'pvc-eb9a2879-5e15-4eaa-a425-6d49ee873e2b' updated for node '192.168.176.22'.
01:31:33.527 [DeviceManager] INFO  LINSTOR/Satellite - SYSTEM - Aligning size from 1048840 KiB to 1052672 KiB to be a multiple of extent size 4096 KiB
01:31:33.757 [DeviceManager] ERROR LINSTOR/Satellite - SYSTEM - Generated resource file for resource 'pvc-eb9a2879-5e15-4eaa-a425-6d49ee873e2b' is invalid. [Report number 64657461-E5C9B-000035]

01:33:33.517 [MainWorkerPool-4] ERROR LINSTOR/Satellite - SYSTEM - Failed to fetch allocated size of /var/lib/piraeus-datastore/pool1/pvc-e0742dd5-f120-4582-a91c-0272c772b374_00000.img [Report number 64657461-E5C9B-000036]
`

storage pool are ok

` kubectl -n piraeus-datastore exec deploy/linstor-controller -- linstor storage-pool list
+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| StoragePool          | Node            | Driver    | PoolName                         | FreeCapacity | TotalCapacity | CanSnapshots | State | SharedName |
|==========================================================================================================================================================|
| DfltDisklessStorPool | 192.168.176.183 | DISKLESS  |                                  |              |               | False        | Ok    |            |
| DfltDisklessStorPool | 192.168.176.22  | DISKLESS  |                                  |              |               | False        | Ok    |            |
| device-pool          | 192.168.176.183 | LVM       | linstor-pool                     |    20.00 GiB |     20.00 GiB | False        | Ok    |            |
| device-pool          | 192.168.176.22  | LVM       | linstor-pool                     |    20.00 GiB |     20.00 GiB | False        | Ok    |            |
| pool1                | 192.168.176.183 | FILE_THIN | /var/lib/piraeus-datastore/pool1 |    81.58 GiB |     91.40 GiB | False        | Ok    |            |
| pool1                | 192.168.176.22  | FILE_THIN | /var/lib/piraeus-datastore/pool1 |    82.30 GiB |     91.40 GiB | False        | Ok    |            |
+----------------------------------------------------------------------------------------------------------------------------------------------------------+
`

**Comment by WanzenBug** [comment]
Please provide the error reports (`linstor error-reports show 64657461-E5C9B-000035`). It looks like the volume is not set up correctly.

**Comment by little-guy-lxr** [comment]
> Please provide the error reports (`linstor error-reports show 64657461-E5C9B-000035`). It looks like the volume is not set up correctly.


 kubectl -n piraeus-datastore exec deploy/linstor-controller -- linstor error-reports show 64671D1A-E5C9B-000000

ERROR REPORT 64671D1A-E5C9B-000000

============================================================

Application:                        LINBIT�� LINSTOR
Module:                             Satellite
Version:                            1.22.0
Build ID:                           0dd2e7d8bad7b0115e924ef66371568320898285
Build time:                         2023-04-17T11:24:18+00:00
Error time:                         2023-05-19 06:55:05
Node:                               192.168.176.183

============================================================

Reported error:
===============

Description:
    Operations on resource 'pvc-7a225b8e-3b85-4905-bc80-c862fcb4b116' were aborted
Cause:
    Verification of resource file failed
Additional information:
    The error reported by the runtime environment or operating system is:
    The external command 'drbdadm' exited with error code 10

Category:                           LinStorException
Class name:                         StorageException
Class canonical name:               com.linbit.linstor.storage.StorageException
Generated at:                       Method 'regenerateResFile', Source file 'DrbdLayer.java', Line #1673

Error message:                      Generated resource file for resource 'pvc-7a225b8e-3b85-4905-bc80-c862fcb4b116' is invalid.

Error context:
    An error occurred while processing resource 'Node: '192.168.176.183', Rsc: 'pvc-7a225b8e-3b85-4905-bc80-c862fcb4b116''

ErrorContext:   Description: Operations on resource 'pvc-7a225b8e-3b85-4905-bc80-c862fcb4b116' were aborted
  Cause:       Verification of resource file failed
  Details:     The error reported by the runtime environment or operating system is:
The external command 'drbdadm' exited with error code 10



Call backtrace:

    Method                                   Native Class:Line number
    regenerateResFile                        N      com.linbit.linstor.layer.drbd.DrbdLayer:1673
    adjustDrbd                               N      com.linbit.linstor.layer.drbd.DrbdLayer:664
    process                                  N      com.linbit.linstor.layer.drbd.DrbdLayer:424
    process                                  N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:983
    processResourcesAndSnapshots             N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:411
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:175
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:323
    phaseDispatchDeviceHandlers              N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:1153
    devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:751
    run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:645
    run                                      N      java.lang.Thread:829

Caused by:
==========

Description:
    Execution of the external command 'drbdadm' failed.
Cause:
    The external command exited with error code 10.
Correction:
    - Check whether the external program is operating properly.
    - Check whether the command line is correct.
      Contact a system administrator or a developer if the command line is no longer valid
      for the installed version of the external program.
Additional information:
    The full command line executed was:
    drbdadm --config-to-test /var/lib/linstor.d/pvc-7a225b8e-3b85-4905-bc80-c862fcb4b116.res_tmp --config-to-exclude /var/lib/linstor.d/pvc-7a225b8e-3b85-4905-bc80-c862fcb4b116.res sh-nop

    The external command sent the following output data:


    The external command sent the following error information:
    /var/lib/linstor.d/pvc-7a225b8e-3b85-4905-bc80-c862fcb4b116.res_tmp:27: Parse error: 'TK_STRING | '{'' expected,
    	but got '192.168.176.183' (TK 279)


Category:                           LinStorException
Class name:                         ExtCmdFailedException
Class canonical name:               com.linbit.extproc.ExtCmdFailedException
Generated at:                       Method 'execute', Source file 'DrbdAdm.java', Line #593

Error message:                      The external command 'drbdadm' exited with error code 10


ErrorContext:   Description: Execution of the external command 'drbdadm' failed.
  Cause:       The external command exited with error code 10.
  Correction:  - Check whether the external program is operating properly.
- Check whether the command line is correct.
  Contact a system administrator or a developer if the command line is no longer valid
  for the installed version of the external program.
  Details:     The full command line executed was:
drbdadm --config-to-test /var/lib/linstor.d/pvc-7a225b8e-3b85-4905-bc80-c862fcb4b116.res_tmp --config-to-exclude /var/lib/linstor.d/pvc-7a225b8e-3b85-4905-bc80-c862fcb4b116.res sh-nop

The external command sent the following output data:


The external command sent the following error information:
/var/lib/linstor.d/pvc-7a225b8e-3b85-4905-bc80-c862fcb4b116.res_tmp:27: Parse error: 'TK_STRING | '{'' expected,
	but got '192.168.176.183' (TK 279)




Call backtrace:

    Method                                   Native Class:Line number
    execute                                  N      com.linbit.linstor.layer.drbd.utils.DrbdAdm:593
    execute                                  N      com.linbit.linstor.layer.drbd.utils.DrbdAdm:579
    checkResFile                             N      com.linbit.linstor.layer.drbd.utils.DrbdAdm:446
    regenerateResFile                        N      com.linbit.linstor.layer.drbd.DrbdLayer:1666
    adjustDrbd                               N      com.linbit.linstor.layer.drbd.DrbdLayer:664
    process                                  N      com.linbit.linstor.layer.drbd.DrbdLayer:424
    process                                  N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:983
    processResourcesAndSnapshots             N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:411
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:175
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:323
    phaseDispatchDeviceHandlers              N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:1153
    devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:751
    run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:645
    run                                      N      java.lang.Thread:829


END OF ERROR REPORT.

**Comment by WanzenBug** [comment]
A simpler solution/workaround would be to use proper hostnames instead of IP Addresses for your kubernetes nodes. So instead of naming them 192.168.176.183, you could name them "node-183" or similar.

**Comment by little-guy-lxr** [comment]
> A simpler solution/workaround would be to use proper hostnames instead of IP Addresses for your kubernetes nodes. So instead of naming them 192.168.176.183, you could name them "node-183" or similar.

@WanzenBug Thank you. That works after I modified the hostname instead of IP Addresses.

**Comment by little-guy-lxr** [comment]
@WanzenBug  Do you know where to file an issue? 

https://github.com/LINBIT/drbd-utils/issues/29#issuecomment-1556993454

**Comment by WanzenBug** [comment]
I guess that was an https://github.com/linbit/linstor-server issue after all. 

It is already fixed in LINSTOR 1.23.0: https://github.com/LINBIT/linstor-server/commit/fcdf85c5fe1a0c7d8a866095d9354d7473811bae

An updated Operator will be released this week.
