### ISSUE TITLE
Applying Piraeus Operator manifests, k8s suggest some security context to be set.

### ISSUE THREAD

**Issue by bmbeverst** [piraeusdatastore/piraeus-operator#474]
Good day,

Trying to set up Piraeus since it is a great persistent storage provider with HA and low resource. I am following this tutorial [Get Started](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/tutorial/get-started.md). I was able to install `cert-manager` without any issues.  My Kubernetes cluster uses the `PodSecurity "restricted:latest"` and I can't deploy piraeus-operator due to PodSecurity violations that block the creation of the `kube-rbac-proxy` and `manager` containers.

I tried to work around the issues by labeling the `piraeus-datastore` namespace as `pod-security.kubernetes.io/enforce: privileged` and tried adding the `securityContext` to the manifest myself. But neither of the approaches worked. 

Recommended security context:
```
Warning: would violate PodSecurity "restricted:latest":
allowPrivilegeEscalation != false (container "kube-rbac-proxy" must set securityContext.allowPrivilegeEscalation=false), 
unrestricted capabilities (containers "manager", "kube-rbac-proxy" must set securityContext.capabilities.drop=["ALL"]), 
seccompProfile (pod or containers "manager", "kube-rbac-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

Can you please add the recommended `securityContext` to piraeus-operator?

**Comment by WanzenBug** [comment]
The piraeus-operator should definitely comply with the `restricted` policy. 

But we also definitely need `privileged` for the other components (can't mount volumes without privileged containers).

So I wonder what went wrong when labelling the namespace :thinking: I guess we should also enforce that in our manifests.

**Comment by bmbeverst** [comment]
Thanks for the help!

I think I see the issue. I used [this guide](https://docs.k3s.io/security/hardening-guide) to harden the service and I notice that it is using the `v1beta1` apiVersion for PodSecurity.

I will try updating that to `latest` and see if the issue is resolved. I have been having issues with a lot of deployments and this would explain why.

**Comment by bmbeverst** [comment]
Got it to work. The hardening documents I was following were for 1.24 or 1.23 so I updated that section. I also added `piraeus-datastore` namespace as exempt to [Pod Security Admission Controller](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/). 

```
timed out waiting for the condition on pods/linstor-controller-97cd7495c-qmmmr
timed out waiting for the condition on pods/linstor-csi-controller-69f85cf594-wp7l2
timed out waiting for the condition on pods/linstor-csi-node-62fph
timed out waiting for the condition on pods/linstor-csi-node-fvmlk
timed out waiting for the condition on pods/linstor-csi-node-hmck9
timed out waiting for the condition on pods/netes-master1
timed out waiting for the condition on pods/netes-master2
timed out waiting for the condition on pods/netes-master3
timed out waiting for the condition on pods/piraeus-operator-controller-manager-5669d497c6-zkr4c
```

Getting timeouts now but that is not related to the
