### ISSUE TITLE
Create a LinstorClusterservice - "webhook-service" not found ( failed to call webhook)

### ISSUE THREAD

**Issue by Andrey-Ganzenko** [piraeusdatastore/piraeus-operator#496]
What could be the problem?

kubectl apply -f - <<EOF                                                                       
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec: {}
EOF
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "vlinstorcluster.kb.io": failed to call webhook: Post "https://webhook-service.system.svc:443/validate-piraeus-io-v1-linstorcluster?timeout=10s": service "webhook-service" not found

**Comment by WanzenBug** [comment]
How did you deploy the operator itself? The service name should be `piraeus-operator-webhook-service.piraeus-datastore.svc`. That is uses the `system` namespace also indicates that you did not use the provided default `config/default/kustomization.yaml`.

**Comment by Andrey-Ganzenko** [comment]
deploy the operator 
kubectl apply --server-side -k "https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2"

**Comment by WanzenBug** [comment]
Works for me as expected:
```
$ kubectl apply --server-side -k "https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2"
namespace/piraeus-datastore serverside-applied
customresourcedefinition.apiextensions.k8s.io/linstorclusters.piraeus.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/linstorsatelliteconfigurations.piraeus.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/linstorsatellites.piraeus.io serverside-applied
serviceaccount/piraeus-operator-controller-manager serverside-applied
serviceaccount/piraeus-operator-gencert serverside-applied
role.rbac.authorization.k8s.io/piraeus-operator-gencert serverside-applied
role.rbac.authorization.k8s.io/piraeus-operator-leader-election-role serverside-applied
clusterrole.rbac.authorization.k8s.io/piraeus-operator-controller-manager serverside-applied
clusterrole.rbac.authorization.k8s.io/piraeus-operator-gencert serverside-applied
rolebinding.rbac.authorization.k8s.io/piraeus-operator-gencert serverside-applied
rolebinding.rbac.authorization.k8s.io/piraeus-operator-leader-election-rolebinding serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/piraeus-operator-gencert serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/piraeus-operator-manager-rolebinding serverside-applied
configmap/piraeus-operator-image-config serverside-applied
service/piraeus-operator-webhook-service serverside-applied
deployment.apps/piraeus-operator-controller-manager serverside-applied
deployment.apps/piraeus-operator-gencert serverside-applied
validatingwebhookconfiguration.admissionregistration.k8s.io/piraeus-operator-validating-webhook-configuration serverside-applied
$ kubectl apply -f - <<EOF
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec: {}
EOF
linstorcluster.piraeus.io/linstorcluster created
```

Are you using an old version of kubectl?

**Comment by Andrey-Ganzenko** [comment]
kubectl version v1.27.3

kubectl delete -k "https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2"
namespace "piraeus-datastore" deleted
customresourcedefinition.apiextensions.k8s.io "linstorclusters.piraeus.io" deleted
customresourcedefinition.apiextensions.k8s.io "linstorsatelliteconfigurations.piraeus.io" deleted
customresourcedefinition.apiextensions.k8s.io "linstorsatellites.piraeus.io" deleted
serviceaccount "piraeus-operator-controller-manager" deleted
serviceaccount "piraeus-operator-gencert" deleted
role.rbac.authorization.k8s.io "piraeus-operator-gencert" deleted
role.rbac.authorization.k8s.io "piraeus-operator-leader-election-role" deleted
clusterrole.rbac.authorization.k8s.io "piraeus-operator-controller-manager" deleted
clusterrole.rbac.authorization.k8s.io "piraeus-operator-gencert" deleted
rolebinding.rbac.authorization.k8s.io "piraeus-operator-gencert" deleted
rolebinding.rbac.authorization.k8s.io "piraeus-operator-leader-election-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "piraeus-operator-gencert" deleted
clusterrolebinding.rbac.authorization.k8s.io "piraeus-operator-manager-rolebinding" deleted
configmap "piraeus-operator-image-config" deleted
service "piraeus-operator-webhook-service" deleted
deployment.apps "piraeus-operator-controller-manager" deleted
deployment.apps "piraeus-operator-gencert" deleted
validatingwebhookconfiguration.admissionregistration.k8s.io "piraeus-operator-validating-webhook-configuration" deleted

kubectl apply --server-side -k "https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2"
namespace/piraeus-datastore serverside-applied
customresourcedefinition.apiextensions.k8s.io/linstorclusters.piraeus.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/linstorsatelliteconfigurations.piraeus.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/linstorsatellites.piraeus.io serverside-applied
serviceaccount/piraeus-operator-controller-manager serverside-applied
serviceaccount/piraeus-operator-gencert serverside-applied
role.rbac.authorization.k8s.io/piraeus-operator-gencert serverside-applied
role.rbac.authorization.k8s.io/piraeus-operator-leader-election-role serverside-applied
clusterrole.rbac.authorization.k8s.io/piraeus-operator-controller-manager serverside-applied
clusterrole.rbac.authorization.k8s.io/piraeus-operator-gencert serverside-applied
rolebinding.rbac.authorization.k8s.io/piraeus-operator-gencert serverside-applied
rolebinding.rbac.authorization.k8s.io/piraeus-operator-leader-election-rolebinding serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/piraeus-operator-gencert serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/piraeus-operator-manager-rolebinding serverside-applied
configmap/piraeus-operator-image-config serverside-applied
service/piraeus-operator-webhook-service serverside-applied
deployment.apps/piraeus-operator-controller-manager serverside-applied
deployment.apps/piraeus-operator-gencert serverside-applied
validatingwebhookconfiguration.admissionregistration.k8s.io/piraeus-operator-validating-webhook-configuration serverside-applied

kubectl get deployments -n piraeus-datastore
NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
piraeus-operator-controller-manager   1/1     1            1           2m34s
piraeus-operator-gencert              1/1     1            1           2m34s

 kubectl get deployments -n cert-manager
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
cert-manager              1/1     1            1           13h
cert-manager-cainjector   1/1     1            1           13h
cert-manager-webhook      1/1     1            1           13h

kubectl apply -f - <<EOF
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec: {}
EOF
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "vlinstorcluster.kb.io": failed to call webhook: Post "https://piraeus-operator-webhook-service.piraeus-datastore.svc:443/validate-piraeus-io-v1-linstorcluster?timeout=10s": context deadline exceeded

**Comment by Andrey-Ganzenko** [comment]
@WanzenBug , Thank you for your time!
The problem was related to CNI Flannel
