### ISSUE TITLE
drbd reactor back-off restarting failed container

### ISSUE THREAD

**Issue by borisovnn** [piraeusdatastore/piraeus-operator#497]
Log: [DeviceManager] ERROR LINSTOR/Satellite - SYSTEM - Need initial DRBD state

**Comment by borisovnn** [comment]
configuration: 
    - apiVersion: piraeus.io/v1
      kind: LinstorCluster
      metadata:
        name: linstorcluster
      spec:{}
    - apiVersion: piraeus.io/v1
      kind: LinstorSatelliteConfiguration
      metadata:
        name: storage-pool
      spec:{}
        storagePools:
          - name: pool
            fileThinPool:
              directory: /mnt/hdd
    - apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: piraeus-storage
      provisioner: linstor.csi.linbit.com
      allowVolumeExpansion: true
      volumeBindingMode: WaitForFirstConsumer
      parameters:
        linstor.csi.linbit.com/placementCount: "3"
        linstor.csi.linbit.com/storagePool: pool

**Comment by WanzenBug** [comment]
Looks like you somehow managed to start the cluster without having DRBD available.

Can you check the logs of the `drbd-module-loader` container of the satellite pods. It should show something like:
```
DRBD version loaded:
version: 9.2.4 (api:2/proto:86-122)
GIT-hash: 460cfc1025ba5abb63ac9ed2895d6cec178bb39c build by @some-node, 2023-06-27 10:32:07
Transports (api:18): tcp (9.2.4) rdma (9.2.4)
```

**Comment by borisovnn** [comment]
Hello!
DRBD version loaded:
version: 8.4.11 (api:1/proto:86-101)
srcversion: A2B7326333D8D6BCA07314C

**Comment by borisovnn** [comment]
> Looks like you somehow managed to start the cluster without having DRBD available.
> 
> Can you check the logs of the `drbd-module-loader` container of the satellite pods. It should show something like:
> 
> ```
> DRBD version loaded:
> version: 9.2.4 (api:2/proto:86-122)
> GIT-hash: 460cfc1025ba5abb63ac9ed2895d6cec178bb39c build by @some-node, 2023-06-27 10:32:07
> Transports (api:18): tcp (9.2.4) rdma (9.2.4)
> ```

**Comment by WanzenBug** [comment]
I guess there is your problem. You need DRBD 9+. If you use ubuntu as base image it may load DRBD 8 .4 initially. You need to `rmmod drbd` on all nodes, and then delete all the satellite pods. Then it should load the new DRBD version.

If you installed `drbd-utils` on the host, you also need to `systemctl disable --now drbd.service`. Ubuntu starts setting up DRBD at boot, which will also load the wrong DRBD version on every boot.

**Comment by borisovnn** [comment]
It's work, Thank You!
