### ISSUE TITLE
Feature request: Encrypted communication

### ISSUE THREAD

**Issue by tbykowsk** [piraeusdatastore/piraeus-operator#5]
Please consider providing an option to enable encrypted communication (_https_) between Linstor components.
Ideally, this could also include the communication within and to an _etcd_ database cluster, which is used by a Linstor Controller.

**Comment by JoelColledge** [comment]
So there are many parts to this, as you have already indicated:
* Linstor Client - Controller: For this, the user will need access to a certificate to be able to connect. Do you know how this is typically solved? I'm assume the user would be expected to supply a certificate in a secret or something of that nature. The Operator and CSI driver would also need to be supplied with the necessary certificate to be able to connect to the Controller.
* Linstor Controller - Satellite: The operator could configure this without any interaction from the user.
* Linstor Controller - etcd cluster: This probably also requires certificates from the user, because they need to be able to access the etcd cluster directly as well.
* Within etcd cluster: This is outside the scope of the operator itself. The Helm chart should allow it already just using the `auth.peer` options [documented here](https://github.com/bitnami/charts/tree/master/bitnami/etcd), but with the `etcd.` prefix for the keys.

**Comment by tbykowsk** [comment]
In cases when a key is required from the user, a common practice is to create a Certificate Signing Request for this key, using `certificates.k8s.io` API - which provides you with a TLS certificate signed by a Certificate Authority. Then you usually supply the key/certificate to pods using secrets.

Thank you for pointing out that the etcd cluster is an external dependency. Indeed, I see that communication within the cluster might be set separately via `etcd-env-vars` ConfigMap (from the examples). If a Linstor Controller could be configured by the operator to communicate with the etcd using a certificate provided by a secret, then it would be great.

**Comment by JoelColledge** [comment]
@WanzenBug Has implemented a solution for the "Linstor Controller - etcd cluster" part so it should now be possible to encrypt all communication with and within the etcd cluster.

**Comment by JoelColledge** [comment]
#13 implements the "Linstor Controller - Satellite" part.

**Comment by WanzenBug** [comment]
I have a question in regards to this request. @tbykowsk, I hope you can help us answer it!

When you say:
>  enable encrypted communication
does that mean:
1. Components talk via encrypted channels (HTTPS, TLS, etc)
2. Components talk via encrypted channels (HTTPS, TLS, etc), which is **_also_** used for authentication

The currently merged changes only address the 1st option. For example, when securely connecting to an `etcd` instance, linstor will use HTTPS, but it will not present its own certificate to authenticate on `etcd`. The same is true for the current controller <-> satellite communication: it can be secured using TLS, but there is no particular authentication other than "we both trust the others certificate".

While option 2 is possible to implement it would involve a lot of moving parts, especially in the Linstor Client <-> Controller communication

**Comment by tbykowsk** [comment]
Thank you for your contributions @WanzenBug!

The ideal solution would be to have encryption and authentication.
It would still be a security threat if anyone could connect to the components, even while using encrypted communication.
If authentication of certificates involves a lot of moving parts, maybe there is a way to provide authentication based on password - which could be kept in a secret.

**Comment by WanzenBug** [comment]
Just a small status update:
From our understanding, the authentication part is actually already covered in the current implementation of LINSTOR controller <-> satellite communication (as described in `doc/security.md`):
* The controller has a private key + a single public key that is trusted (the satellite's key)
* The satellite has a private key + a single public key that is trusted (the controller's key)

I will work on the missing parts, namely:
* authentication against `etcd` using certs
* HTTPS + auth for the linstor client api

**Comment by WanzenBug** [comment]
etcd HTTPS+auth implemented: [docs](https://github.com/piraeusdatastore/piraeus-operator/blob/master/doc/security.md#secure-communication-with-an-existing-etcd-instance)
linstor client HTTPS+auth implemented: [docs](https://github.com/piraeusdatastore/piraeus-operator/blob/master/doc/security.md#configuring-secure-communications-for-the-linstor-api)

**Comment by tbykowsk** [comment]
Thank you @WanzenBug!
Does this [configuration](https://github.com/piraeusdatastore/piraeus-operator/blob/master/doc/security.md#configuring-secure-communication-between-linstor-components) also include communication between Linstor-CSI and Linstor Controller, or it has to be set up separately?

**Comment by WanzenBug** [comment]
Linstor-CSI is also set up with HTTPS (in fact, any client not configured with the certificate will be rejected)

**Comment by JoelColledge** [comment]
@tbykowsk I've pushed a new image to `quay.io/piraeusdatastore/piraeus-operator:latest`. Please try it out and close this issue if everything is working. Thanks!

**Comment by tbykowsk** [comment]
Communication between all components is encrypted and authenticated.
Thank you so much for your work!

I will think about how [creation of certificates](https://github.com/piraeusdatastore/piraeus-operator/blob/master/doc/security.md) could be further automated, but that will be for another feature request :)
