### ISSUE TITLE
deploy v2 cluster error failed to create typed patch object: .spec.ipFamilyPolicy: field not declared in schema

### ISSUE THREAD

**Issue by Icedroid** [piraeusdatastore/piraeus-operator#511]
I follow the get start document:
https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/tutorial/get-started.md
after step 2 I got error as follow:

>ERROR	Reconciler error	{"controller": "linstorcluster", "controllerGroup": "piraeus.io", "controllerKind": "LinstorCluster", "LinstorCluster": {"name":"linstorcluster"}, "namespace": "", "name": "linstorcluster", "reconcileID": "7796d36a-dfe7-4e1e-a9dc-9a4f74714396", "error": "failed to create typed patch object: .spec.ipFamilyPolicy: field not declared in schema"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235
2023-08-01T15:38:40Z	ERROR	Reconciler error	{"controller": "linstorsatellite", "controllerGroup": "piraeus.io", "controllerKind": "LinstorSatellite", "LinstorSatellite": {"name":"192.168.212.70"}, "namespace": "", "name": "192.168.212.70", "reconcileID": "3de77c29-2dc6-4959-8a46-81004114a455", "error": "pods \"192.168.212.70\" is forbidden: error looking up service account piraeus-datastore/satellite: serviceaccount \"satellite\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235

**Comment by WanzenBug** [comment]
What's your kubernetes version? I believe the `.spec.ipFamilyPolicy` field was added with Kubernetes 1.21...

**Comment by Icedroid** [comment]
I use Kubernetes 1.18, V2 version not support?

**Comment by WanzenBug** [comment]
No. While we don't actively try to break anything, we only test with what the Kubernetes project considers maintained and "stable" releases. Which are currently 1.27, 1.26, 1.25 and 1.24.
