### ISSUE TITLE
Different hostDevices on each LinstorSatellite

### ISSUE THREAD

**Issue by online01993** [piraeusdatastore/piraeus-operator#526]
Hello,
I've read a bunch of docs and a bit confused too [#226](https://github.com/piraeusdatastore/piraeus-operator/issues/226).
I have a similar question but slightly different.

I have setup 9 node cluster k8s that has:
- 3 control-plane nodes that should not launch satellites
- 2 worker nodes that should launch satellites with ssd-pool, one node has hostDevices /dev/sd**B** another node has devicePath /dev/sd**C** 
- 2 worker nodes that should launch satellites with hdd-pool, one node has hostDevices /dev/sd**D** another node has devicePath /dev/sd**E**

What settings do I need to apply to my cluster for this? Considering the main difficulty is that the hostDevices is unique on each node

**Comment by WanzenBug** [comment]
Luckily, this all got a bit easier with Operator v2:

First, to exclude the control-plane nodes, you should set a [`nodeSelector`](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/reference/linstorcluster.md#specnodeselector) on the LinstorCluster.

For your workers, you can create [`LinstorSatelliteConfiguration`](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/reference/linstorsatelliteconfiguration.md#linstorsatelliteconfiguration) resources, one for each node, using the nodeSelector and setting the host path appropriately.

The alternative to setting a LinstorSatelliteConfiguration for every worker node would be to do the pool creation external to Piraeus (i.e. use some other tool like ansible or terraform to run the `pvcreate`, `vgcreate`, `lvcreate` commands) and directly use the generated pools in linstor, not using `hostDevices`.

**Comment by WanzenBug** [comment]
The LinstorCluster resource also creates the LinstorSatellite resource by merging all LinstorSatelliteConfigurations that apply to that satellites. So you need to apply a LinstorSatelliteConfiguration.

And as you have noticed, piraeus-operator does not provide a full featured "disk management" feature. It is generally only intended to get you started. So I'd stick with terraform :)

**Comment by online01993** [comment]
@WanzenBug in general, I understand, thank you for your help, I’ll try to change my configuration to use separate LinstorSatelliteConfiguration.
But I would like, with your help, to understand how to use the LinstorSatellite resource. When I use LinstorSatellite resource, it will not create, because the name is already occupied by the resource that Linstorcluster created

**Comment by WanzenBug** [comment]
The `LinstorSatellite` resource is basically "internal". You can view it to see what the Operator tries to create, but you cannot change it manually.

The Operator will see the `LinstorCluster` resource, and for every node matching the `nodeSelector` it will create a `LinstorSatellite` resource. You can influence how that `LinstorSatellite` resource looks like by using the `LinstorSatelliteConfiguration` resources.

**Comment by online01993** [comment]
@WanzenBug 
Now everything is clear! Thanks again!

**Comment by online01993** [comment]
> The `LinstorSatellite` resource is basically "internal". You can view it to see what the Operator tries to create, but you cannot change it manually.
> 
> The Operator will see the `LinstorCluster` resource, and for every node matching the `nodeSelector` it will create a `LinstorSatellite` resource. You can influence how that `LinstorSatellite` resource looks like by using the `LinstorSatelliteConfiguration` resources.

I think this would be a good idea to add to the documentation
