### ISSUE TITLE
linstor-controller pod has no drbdadm resource definitions

### ISSUE THREAD

**Issue by zrav** [piraeusdatastore/piraeus-operator#555]
After following the tutorial/how-to to set up a linstor cluster, the result is a setup that is manageable through the "linstor" command in the linstor-controller pod. This pod also provides the drbdadm tool, needed for direct DRBD interaction (for troubleshooting, for example), however it comes with an empty configuration, i.e. no resource definitions. What is the expected way to provide drbdadm with the needed configuration? If the recommendation is that users install and use drbdadm directly on the k8s host instead of the controller pod, what is the best practice to keep the resource definition config in sync with the one being updated through the piraeus operator? I believe I'm lacking a vital piece of information not provided by the piraeus documentation.

**Comment by WanzenBug** [comment]
You want to use the satellite pods (they are the pods named after your node names). These have all the DRBD configuration and also `drbdadm` installed.
