### ISSUE TITLE
Enable linstor-controller to run with multiple replicas

### ISSUE THREAD

**Issue by WanzenBug** [piraeusdatastore/piraeus-operator#56]
For HA we want to have multiple instances of a LINSTOR controller running, with internal leader election to determine the active one.

This is part of #55.
See also the discussion around #50, #52, #53

**Comment by dimm0** [comment]
Is this supported? There's no `replicas` field in the linstorcluster spec.controller CRD

**Comment by WanzenBug** [comment]
No, it was always a hack. There can only be one controller running at a time. The way we achieve faster failover is using tolerations that cause the Pod to be quickly rescheduled should the node experience issues.

**Comment by dimm0** [comment]
It takes a couple minutes for my pod to start.. we have more than 1000 volumes in the cluster.

But ok, thanks for the info
