### ISSUE TITLE
how to bump

### ISSUE THREAD

**Issue by tampler** [piraeusdatastore/piraeus-operator#593]
Hello thanks for building and supporting this software. This is a request for docs update :point_up: 

 I started to use it and am pretty happy :smile:  with it. My concern is how to **bump** it, say from `v2.3.0` to `v2.3.2`.

Many vital resources are dependent on storage. Is there a safe way to bump this without loosing `pvc` and thus all data? :thinking:

**Comment by WanzenBug** [comment]
In general, upgrading is just applying the new version of the manifests. Existing PVCs and storage configuration will continue to work. But you are right, that should be explained in the docs.

**Comment by tampler** [comment]
Let's summarize. If I want to bump from `v2.3.0` to `v2.3.1` when its released:

1. I do: 
`kubectl apply --server-side -k "https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2.3.1`"`
2. I do NOT do: 
```sh
kubectl delete --server-side -k "https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2.3.0"`
kubectl apply --server-side -k "https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2.3.1"
```
Is that the right way ? :thinking: I'm afraid I'll be loosing all my `pvc` if I do `kubectl delete`

**Comment by WanzenBug** [comment]
Yes, just the `apply` command is enough. Even if you accidentally run `delete` and then `apply`, you won't lose your data. You might need to do some manual clean-up to get everything into working order, but your PVCs won't be affected.

**Comment by WanzenBug** [comment]
See https://github.com/piraeusdatastore/piraeus-operator/blob/v2/UPGRADE.md
