### ISSUE TITLE
disabled-nodes LinstorSatelliteConfiguration is not working

### ISSUE THREAD

**Issue by jonathon2nd** [piraeusdatastore/piraeus-operator#599]
Using this [yaml](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/reference/linstorsatelliteconfiguration.md#example-1) does not work. I must be missing something obvious. 

![image](https://github.com/piraeusdatastore/piraeus-operator/assets/52681917/58395c70-67fd-4d84-a5eb-d5a849bac756)

![image](https://github.com/piraeusdatastore/piraeus-operator/assets/52681917/77e03a41-2168-4988-bc83-ab27b7b8d5b4)

![image](https://github.com/piraeusdatastore/piraeus-operator/assets/52681917/e2aafd7b-bb02-4cab-9f15-c686423989d1)

labels from one of the hosts
![image](https://github.com/piraeusdatastore/piraeus-operator/assets/52681917/16aeacf5-5282-4526-b814-376f83664bd6)

**Comment by WanzenBug** [comment]
I think what you want is the nodeAffinity setting on the [`LinstorCluster`](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/reference/linstorcluster.md#specnodeaffinity). The satellites are deployed to all nodes by default, the satellite configuration affinity only controls which configuration applies to which set of satellites.

**Comment by jonathon2nd** [comment]
That was it, thanks!
