### ISSUE TITLE
Deployment on k8s failed due to drbd-module-loader container

### ISSUE THREAD

**Issue by minhtuan-nguyen** [piraeusdatastore/piraeus-operator#636]
Hi,
I tried to deploy piraeus on k8s on-prem cluster but unsuccessful. I saw this error in satellite pod:
  MODPOST /tmp/pkg/drbd-9.2.8/drbd/Module.symvers
  CC [M]  /tmp/pkg/drbd-9.2.8/drbd/drbd-kernel-compat/handshake/handshake.mod.o
  LD [M]  /tmp/pkg/drbd-9.2.8/drbd/drbd-kernel-compat/handshake/handshake.ko
Skipping BTF generation for /tmp/pkg/drbd-9.2.8/drbd/drbd-kernel-compat/handshake/handshake.ko due to unavailability of vmlinux
  BTF [M] /tmp/pkg/drbd-9.2.8/drbd/drbd-kernel-compat/handshake/handshake.ko
  CC [M]  /tmp/pkg/drbd-9.2.8/drbd/drbd.mod.o
  LD [M]  /tmp/pkg/drbd-9.2.8/drbd/drbd.ko
  BTF [M] /tmp/pkg/drbd-9.2.8/drbd/drbd.ko
Skipping BTF generation for /tmp/pkg/drbd-9.2.8/drbd/drbd.ko due to unavailability of vmlinux
  CC [M]  /tmp/pkg/drbd-9.2.8/drbd/drbd_transport_lb-tcp.mod.o
  LD [M]  /tmp/pkg/drbd-9.2.8/drbd/drbd_transport_lb-tcp.ko
  BTF [M] /tmp/pkg/drbd-9.2.8/drbd/drbd_transport_lb-tcp.ko
Skipping BTF generation for /tmp/pkg/drbd-9.2.8/drbd/drbd_transport_lb-tcp.ko due to unavailability of vmlinux
  CC [M]  /tmp/pkg/drbd-9.2.8/drbd/drbd_transport_rdma.mod.o
  LD [M]  /tmp/pkg/drbd-9.2.8/drbd/drbd_transport_rdma.ko
  BTF [M] /tmp/pkg/drbd-9.2.8/drbd/drbd_transport_rdma.ko
Skipping BTF generation for /tmp/pkg/drbd-9.2.8/drbd/drbd_transport_rdma.ko due to unavailability of vmlinux
  CC [M]  /tmp/pkg/drbd-9.2.8/drbd/drbd_transport_tcp.mod.o
  LD [M]  /tmp/pkg/drbd-9.2.8/drbd/drbd_transport_tcp.ko
  BTF [M] /tmp/pkg/drbd-9.2.8/drbd/drbd_transport_tcp.ko
Skipping BTF generation for /tmp/pkg/drbd-9.2.8/drbd/drbd_transport_tcp.ko due to unavailability of vmlinux
mv .drbd_kernelrelease.new .drbd_kernelrelease
Memorizing module configuration ... done.
make[1]: Leaving directory '/tmp/pkg/drbd-9.2.8/drbd'

        Module build was successful.
=======================================================================
  With DRBD module version 8.4.5, we split out the management tools
  into their own repository at https://github.com/LINBIT/drbd-utils
  (tarball at http://links.linbit.com/drbd-download)

  That started out as "drbd-utils version 8.9.0",
  has a different release cycle,
  and provides compatible drbdadm, drbdsetup and drbdmeta tools
  for DRBD module versions 8.3, 8.4 and 9.

  Again: to manage DRBD 9 kernel modules and above,
  you want drbd-utils >= 9.3 from above url.
=======================================================================
insmod: ERROR: could not insert module ./drbd.ko: Key was rejected by service
insmod: ERROR: could not insert module ./drbd_transport_tcp.ko: Key was rejected by service
insmod: ERROR: could not insert module ./drbd_transport_lb-tcp.ko: Key was rejected by service

Could not load DRBD kernel modules

And it keeps crashing.
Any help would be appreciated.

**Comment by WanzenBug** [comment]
I would guess this is caused by the system running with secure boot enabled. Check with `mokutil --sb-state` on the node. You can either disable secure boot, or you need to manually sign the modules. I'm currently in the process of writing a guide on how to do just that.
