### ISSUE TITLE
[bug] The priorityClass of the pods is not set. Cascade of failure ensues.

### ISSUE THREAD

**Issue by bernardgut** [piraeusdatastore/piraeus-operator#654]
The `PriorityClass` of all pods created by the default install method is not set. Nor is there any option and/or documentation in the chart/manifests to set it. I therefore wrongly assumed that it was set,

Today a cluster wend down because some disk pressure caused the linstor-satellite pods to be evicted on a couple of nodes. The result is a cascade of failures that is hard to recover from. Luckily, this happened in a staging cluster so nobody is asking to throw Linstor out of the window yet so we can keep testing and validating.

The priorityClass of all pods created by the operator should be set to `system-node-critical`regardless of if it runs in `kube-system` or not. upstream supports this [for a while now](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/). There is no scenario in which this is not preferable

discuss/

**Comment by WanzenBug** [comment]
You are right, this has been overlooked up to now. 

Do you have any insight on `system-cluster-critical` vs. `system-node-critical`? From my reading, I would guess that the following components are node-critical:
* LINSTOR Controller
* LINSTOR Satellite
* LINSTOR CSI Controller
* LINSTOR CSI node agent

The following are insteadsystem-cluster-critical`:
* Piraeus Operator
* LINSTOR HA Controller

**Comment by bernardgut** [comment]
My understanding is that they are just labels for these two priority values:

- 2000001000 (node)
- 2000000000 (cluster)

The first being the highest possible value. The decision is pretty arbitrary and I think the choice does not matter as much as a value just need to be present to elevate "system" critical pods above workloads in terms of eviction order. 

As far as I know, CSI/CNI projects set one or the other quite arbitrarily. To give you an example, here is a Talos with Cilium and metrics-server default out-of-the-box config (kube-system):
```
cilium-6gfjl    priorityClassName: system-node-critical
cilium-7v4dl    priorityClassName: system-node-critical
cilium-kxz72    priorityClassName: system-node-critical
cilium-operator-576795789c-fxz75    priorityClassName: system-cluster-critical
coredns-85b955d87b-4v8v6   priorityClassName: system-cluster-critical
coredns-85b955d87b-7xcq8   priorityClassName: system-cluster-critical
hubble-relay-78c7874676-w2zbr    priorityClassName: ""
hubble-ui-6548d56557-cgf86    priorityClassName: ""
kube-apiserver-v1    priorityClassName: system-cluster-critical
kube-apiserver-v2    priorityClassName: system-cluster-critical
kube-apiserver-v3    priorityClassName: system-cluster-critical
kube-controller-manager-v1   priorityClassName: system-cluster-critical
kube-controller-manager-v2   priorityClassName: system-cluster-critical
kube-controller-manager-v3   priorityClassName: system-cluster-critical
kube-scheduler-v1    priorityClassName: system-cluster-critical
kube-scheduler-v2    priorityClassName: system-cluster-critical
kube-scheduler-v3    priorityClassName: system-cluster-critical
metrics-server-6d94bc8694-htqk5 priorityClassName: system-cluster-critical
```

So IMO your proposal is fair. If you give me a bunch of pointers as to where in the code you want this I can do the PR myself

thanks
B.

**Comment by WanzenBug** [comment]
Makes sense, thanks!

* The operator deployment itself if found in [`config/manager`](https://github.com/piraeusdatastore/piraeus-operator/tree/v2/config/manager)
* The other components are found in [`pkg/resources/cluster`](https://github.com/piraeusdatastore/piraeus-operator/tree/v2/pkg/resources/cluster) and [`pkg/resources/satellite`](https://github.com/piraeusdatastore/piraeus-operator/tree/v2/pkg/resources/satellite).

I think its fine if we just set these values automatically without additional configuration. Users who want to change that can always use the `podTemplate` or `patch` section.
