### ISSUE TITLE
Linstor Controller crash loop (startup probe is failing) because of space tracking service not running

### ISSUE THREAD

**Issue by RichardSufliarsky** [piraeusdatastore/piraeus-operator#694]
SOLVED - just for the information.

I have encountered issue with too many `SpaceHistory` CRDs: https://lists.linbit.com/pipermail/drbd-user/2024-March/026554.html
Solved it by manually deleting oldest ones.
There were 759 `SpaceHistory` objects when the service stopped working.
Wanted to let you know that the issue was spotted with version: ` quay.io/piraeusdatastore/piraeus-operator:v2.5.1`

I found out that 150 objects were created on 14.6.2024 and at that date I have upgraded to 2.5.1. Maybe it was caused by me, because I was messing (deleting them) with the CRDs for volumes that were not working.

**Comment by WanzenBug** [comment]
This could be of interest for the team over at https://github.com/LINBIT/linstor-server
