### ISSUE TITLE
bug: satellite hyp0 is not ONLINE: OFFLINE

### ISSUE THREAD

**Issue by tampler** [piraeusdatastore/piraeus-operator#754]
I'm trying to install the operator on the fresh kube cluster. I'm reusing scripts which used to work for piraeus-operator v2.5.x version.

Now, `csi-node` and `satellite` pods won't reach the `Running` state, presumably, since the `Cluster` resource can't find the `linstor node`.

Exact logs:
```sh
+ linstor-csi-node-6d766 › linstor-wait-node-online
linstor-csi-node-6d766 linstor-wait-node-online time="2024-12-30T08:18:24Z" level=info msg="not ready" error="Get \"http://linstor-controller:3370/v1/nodes/hyp0\": dial tcp 10.109.213.39:3370: connect: connection refused" version=refs/tags/v0.2.2
linstor-csi-node-6d766 linstor-wait-node-online time="2024-12-30T08:18:34Z" level=info msg="not ready" error="Get \"http://linstor-controller:3370/v1/nodes/hyp0\": dial tcp 10.109.213.39:3370: connect: connection refused" version=refs/tags/v0.2.2
linstor-csi-node-6d766 linstor-wait-node-online time="2024-12-30T08:18:44Z" level=info msg="not ready" error="Get \"http://linstor-controller:3370/v1/nodes/hyp0\": dial tcp 10.109.213.39:3370: connect: connection refused" version=refs/tags/v0.2.2
linstor-csi-node-6d766 linstor-wait-node-online time="2024-12-30T08:18:54Z" level=info msg="not ready" error="Get \"http://linstor-controller:3370/v1/nodes/hyp0\": dial tcp 10.109.213.39:3370: connect: connection refused" version=refs/tags/v0.2.2
linstor-csi-node-6d766 linstor-wait-node-online time="2024-12-30T08:19:04Z" level=info msg="not ready" error="satellite hyp0 is not ONLINE: OFFLINE" version=refs/tags/v0.2.2
linstor-csi-node-6d766 linstor-wait-node-online time="2024-12-30T08:19:14Z" level=info msg="not ready" error="satellite hyp0 is not ONLINE: OFFLINE" version=refs/tags/v0.2.2
linstor-csi-node-6d766 linstor-wait-node-online time="2024-12-30T08:19:24Z" level=info msg="not ready" error="satellite hyp0 is not ONLINE: OFFLINE" version=refs/tags/v0.2.2
```
Piraeus: v2.7.1
OS: Ubuntu 24.04
Containerd: v2.0.1
Kubernetes: v1.32.0

Thanks for any troubleshooting advice in advance :smiley:

**Comment by tampler** [comment]
Getting the same issue for Piraeus v2.6.0. Seems like it can't resolve the `hyp0` name from the request `http://linstor-controller:3370/v1/nodes/hyp0\"

`hyp0` is my hypervisor alias with the RFC1918 addr, e.g. 192.168.1.2 :roll_eyes:

**Comment by WanzenBug** [comment]
Please check with `linstor node list` which IP address it is trying to query. The Operator automatically configures the Pod's address from the `.status.podIPs` field on the Pod.

**Comment by tampler** [comment]
Here's what I have on the `linstor-controller` node:
```sh
LINSTOR ==> n l
╭───────────────────────────────────────────────────────────╮
┊ Node ┊ NodeType  ┊ Addresses                   ┊ State    ┊
╞═══════════════════════════════════════════════════════════╡
┊ hyp0 ┊ SATELLITE ┊ 172.16.197.195:3366 (PLAIN) ┊ EVACUATE ┊
╰───────────────────────────────────────────────────────────╯
```
![linstor-eks](https://github.com/user-attachments/assets/9227e32e-f7bc-417c-b7a2-6aa9ac2dede2)

Seems like `controller` has been trying to reach the `satellite` node, which in turn failed to start :roll_eyes:

**Comment by WanzenBug** [comment]
I guess you need to check the drbd-module-loader container in the linstor-satellite Pod. The logs should tell you why it failed to build and load DRBD.

**Comment by tampler** [comment]
Here you go

```sh
+ linstor-satellite.hyp0-l59jj › drbd-module-loader
linstor-satellite.hyp0-l59jj drbd-module-loader DRBD module is already loaded
linstor-satellite.hyp0-l59jj drbd-module-loader 
linstor-satellite.hyp0-l59jj drbd-module-loader DRBD version loaded:
linstor-satellite.hyp0-l59jj drbd-module-loader version: 9.2.12 (api:2/proto:118-122)
linstor-satellite.hyp0-l59jj drbd-module-loader GIT-hash: 2da6f528dc4ab3fd25c511f7b03531100e54ab08 build by root@hyp0, 2024-12-18 16:49:49
linstor-satellite.hyp0-l59jj drbd-module-loader Transports (api:21):
linstor-satellite.hyp0-l59jj drbd-module-loader 
linstor-satellite.hyp0-l59jj drbd-module-loader - load the drbd module on the host with the module parameter 'usermode_helper=disabled' OR
linstor-satellite.hyp0-l59jj drbd-module-loader - let this container handle that for you by not already loading the drbd module on the host
- linstor-satellite.hyp0-l59jj › drbd-module-loader
```

**Comment by WanzenBug** [comment]
Ok. I gues you have the drbd-dkms installed? Anyways, please create a `/etc/modprobe.d/drbd.conf` with this content:
```
options drbd usermode_helper=disabled
```
Then, to fix it for the current boot, run `echo disabled > /sys/module/drbd/parameters/usermode_helper`

**Comment by tampler** [comment]
Yes, I had `drbd-dkms` installed since I had `Linstor` controller and satellite on the bare metal node before installing  Kubernetes. Let me try and see if that helps :pray:

**Comment by tampler** [comment]
Great! That worked! Thanks a lot @WanzenBug 

This should be also added to docs! Do you accept contribs to docs ? :thinking: 

Thanks a lot for your help and Happy New Year :christmas_tree: 

Vielen Dank für Ihre wunderbare Arbeit :smile:

**Comment by WanzenBug** [comment]
Glad to hear it. :smile: 

> This should be also added to docs! Do you accept contribs to docs ? 🤔

Of course. Feel free to create a PR.
