### ISSUE TITLE
How to on existing ZFS pool?

### ISSUE THREAD

**Issue by nwmcsween** [piraeusdatastore/piraeus-operator#87]
New to linstor and related tooling and was wondering if someone could show me the needed yaml config for adding an existing ZFS pool satellite via pireaus-operator? There seems to be lots of docs on lvm but not much on ZFS.

**Comment by nwmcsween** [comment]
So I had to dig into the actual code on this, the creating a zpool stuff actually creates a zdev on a zpool iirc

**Comment by WanzenBug** [comment]
Hey! Sorry for the delayed response.

Currently the operator has no direct integration for configuring ZFS pools via YAML. You can configure an existing ZFS pool via the LINSTOR client (see [the LINSTOR guide on storage pools here](https://www.linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-storage_pools))

The storage pool will appear in the status field of LinstorSatelliteSet and LinstorController resources. It can be used like a LVM storage pool to configure a storage classes.

**Comment by aland-zhang** [comment]
The recently released [Linstor-server v1.8.0 ](https://github.com/LINBIT/linstor-server/releases/tag/v1.8.0)already supports the ‘zfs create options feature’, and zfs supports high availability similar to raid5. So it is recommended to support adding zfs pools and zfs thin pools in pireaus-operator yaml.

**Comment by WanzenBug** [comment]
Already available in Operator v1, now (#633) also in v2.
