### ISSUE TITLE
Operator fails to update CR status if reconcile timeout is exceeded

### ISSUE THREAD

**Issue by WanzenBug** [piraeusdatastore/piraeus-operator#96]
We use a fixed 1 minute time-out for the whole reconcile loop.
This includes:

1. Setting default values
2. Deploying resources
3. Interacting with the deployed resources
4. Updating the status section of the CR

We should always update our status field, but this may not happen if 1-3 run into a time-out. Especially (3) is prone to such long pauses.

## Proposed solution
The quickest solution is to update the status by passing a new context to `Status().Update(ctx, ...)`
We don't have any external contexts to worry about, so no "external" deadline or expected cancellation.

@JoelColledge opinions?

**Comment by JoelColledge** [comment]
> The quickest solution is to update the status by passing a new context to `Status().Update(ctx, ...)`

Sounds like the right solution to me.
